package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Red Box Expansion",
		Description: "CAH: Red Box Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `_ would only happen in my worst nightmares.`},
			&PromptCard{Prompt: `_: Hours of fun. Easy to use. Perfect for _!`},
			&PromptCard{Prompt: `_. Betcha can't have just one!`},
			&PromptCard{Prompt: `A romantic candlelit dinner would be incomplete without _.`},
			&PromptCard{Prompt: `A superior officer approaches. You salute and say _, and they respond with _.`},
			&PromptCard{Prompt: `after my grandma passed gas, she learned over to my grandpa and said _`},
			&PromptCard{Prompt: `And I would have gotten away with it, too, if it hadn't been for _.`},
			&PromptCard{Prompt: `And what do we say to the God of Death?`},
			&PromptCard{Prompt: `As part of his contract, Prince won't perform without _ in his dressing room.`},
			&PromptCard{Prompt: `As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _.`},
			&PromptCard{Prompt: `Awww, sick! I just say this skater do a 720 kickflip into _!`},
			&PromptCard{Prompt: `Before 1 year of age, the baby should be careful to avoid _.`},
			&PromptCard{Prompt: `Before kids, I never thought about _.`},
			&PromptCard{Prompt: `Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _ in the workplace.`},
			&PromptCard{Prompt: `Charlie and the chocolate _.`},
			&PromptCard{Prompt: `Dear Substitute Teacher, could you please stop _?`},
			&PromptCard{Prompt: `DOCTOR:
What seems to be the problem?

YOU: 
_.`},
			&PromptCard{Prompt: `During high school I never really fit in until I found _ club.`},
			&PromptCard{Prompt: `During his short-lived boxing career, the Messiah fought under the name Jesus "_" Christ.`},
			&PromptCard{Prompt: `Find a _ and pick it up, and all the day you'll have good luck.`},
			&PromptCard{Prompt: `Future Historians will agree that _ marked the beginning of America's decline.`},
			&PromptCard{Prompt: `Having sex with Hillary is like having sex with _.`},
			&PromptCard{Prompt: `Hey baby, come back to my place and I'll show you _.`},
			&PromptCard{Prompt: `I left Hamilton because I heard about _'s obsession with _.`},
			&PromptCard{Prompt: `I love being a mom. But it's tough when my kids come home filthy from _. That's why there's Tide®.`},
			&PromptCard{Prompt: `I spy with my little eye _.`},
			&PromptCard{Prompt: `I went in for a loan and the banker told me _`},
			&PromptCard{Prompt: `I'm sorry, sir, but your insurance plan doesn't cover injuries caused by _.`},
			&PromptCard{Prompt: `If God offered me the afterlife of my choice, I would wrap myself in razor wire and _.`},
			&PromptCard{Prompt: `in a public restroom, someone in the stall next to you grunts _`},
			&PromptCard{Prompt: `In his new summer comedy, Rob Schneider is _ trapped in the body of _.`},
			&PromptCard{Prompt: `In his next movie, Rob Schneider is _.`},
			&PromptCard{Prompt: `In its new tourism campaign, Soweto proudly proclaims that it has finally eliminated _.`},
			&PromptCard{Prompt: `In some cultures, _ is considered a good omen.`},
			&PromptCard{Prompt: `In the UK it's now socially acceptable to have _ in public`},
			&PromptCard{Prompt: `Legend has it Prince wouldn't perform without _ in his dressing room.`},
			&PromptCard{Prompt: `Listen, son. If you want to get involved with _, I won't stop you. Just steer clear of _.`},
			&PromptCard{Prompt: `Live from Universal Studios, it's America's favorite game show! "_ or _?"`},
			&PromptCard{Prompt: `Loyalty, Duty, Respect, Selfless, Service, Honor, Integrity, Personal Courage, and _: the newest Army Value.`},
			&PromptCard{Prompt: `Men are from Mars.  Woman are from _.`},
			&PromptCard{Prompt: `Michelangelo's newest painting is titled _.`},
			&PromptCard{Prompt: `Money from state lotteries goes to _ to buy _.`},
			&PromptCard{Prompt: `My cousin got kicked out of the house after she brought home _.`},
			&PromptCard{Prompt: `My gym teacher got fired for adding _ to the obstacle course.`},
			&PromptCard{Prompt: `My life is ruled by a vicious cycle of _ and _.`},
			&PromptCard{Prompt: `My mom is so happy when I visit, but I'm only there to be _.`},
			&PromptCard{Prompt: `My new favorite sexual position is _.`},
			&PromptCard{Prompt: `My porn-star name would be _; and I'm famous for _.`},
			&PromptCard{Prompt: `Next to ISIS, the biggest threat to global security is _.`},
			&PromptCard{Prompt: `Next week on the Discovery Channel, one man must survive in the depths of the Amazon with only _ and his wits.`},
			&PromptCard{Prompt: `Only you can prevent _.`},
			&PromptCard{Prompt: `Science will never explain the origin of _.`},
			&PromptCard{Prompt: `The Blues have as much chance of winning as _ has at getting laid.`},
			&PromptCard{Prompt: `The CIA reports that Russia is spending billions to influence _.`},
			&PromptCard{Prompt: `The Four Horsemen of the Apocalypse: Pestilence, War, Famine, and _.`},
			&PromptCard{Prompt: `The hills are alive with the sound of _.`},
			&PromptCard{Prompt: `The secret to getting your adopted African street dog back into the United States is _.`},
			&PromptCard{Prompt: `This is your pilot speaking. Please prepare for _.`},
			&PromptCard{Prompt: `This morning when you woke up next to me I thought _.`},
			&PromptCard{Prompt: `To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _.`},
			&PromptCard{Prompt: `Tonight on Police 10 7 we're chasing _, rumoured to be responsible for _.`},
			&PromptCard{Prompt: `Twas the night before Christmas, and all through the house,

not a creature was stirring, not even _.`},
			&PromptCard{Prompt: `Welcome to Senor Frog's! Would you like to try our signature cocktail, "_ on the Beach"?`},
			&PromptCard{Prompt: `What came in the mail today?`},
			&PromptCard{Prompt: `What has been seen cannot be unssen! I just witnessed _.`},
			&PromptCard{Prompt: `What made me this way?`},
			&PromptCard{Prompt: `What's holding you back from achieving your dreams?`},
			&PromptCard{Prompt: `When asked about the biggest threat facing the nation, 60% of Americans said _.`},
			&PromptCard{Prompt: `When i pooped, what came out?`},
			&PromptCard{Prompt: `When you go to the polls on Tuesday, remember:  a vote for me is a vote for _.`},
			&PromptCard{Prompt: `With every year that passes, I find it harder and harder to be _.`},
			&PromptCard{Prompt: `You hear the craziest stuff in methadone clinic lineups, this morning I overheard "Insert Name" having a heated conversations about _.`},
			&PromptCard{Prompt: `Your security clearance has been suspended beause of your shameful past involving _.`},
		},

		Responses: []ResponseCard{
			`25 shitty jokes about House of Cards.`,
			`A 6-hour conversation on gender and queer theory.`,
			`A big black dildo.`,
			`A bigger, blacker knitting bag.`,
			`A black-owned and operated business.`,
			`A blow job from Shark Girl, with teeth.`,
			`A boomtown whore.`,
			`A botched genital piercing.`,
			`A burning orphanage.`,
			`A cat with... hands.`,
			`A complicated relationship with food.`,
			`A copy of Bedside Hitler.`,
			`A Craptrap`,
			`A dollw that pees real pee!`,
			`A fat Batman with a sopping wet scrotum.`,
			`A fortune cookie containing a wasp.`,
			`A greasy pork sandwich served on a dirty ashtray.`,
			`A Japanese tourist who wants something very badly but cannot communicate it.`,
			`A Japanese whaling operation.`,
			`A LAN party.`,
			`a low sucking sound`,
			`A magical cupboard that brings sex toys to life.`,
			`A man of means by no means.`,
			`A nautical theme.`,
			`A Nuclear Deterrence Operations Service Medal that somehow gives your worthless life meaning.`,
			`A paternity test.`,
			`A phantasmagoria of anal delights.`,
			`a pillow biter`,
			`A pineapple with chlamydia.`,
			`A pocket diaper.`,
			`A prayer bouquet.`,
			`A sad god with a shit-covered pair of nipples.`,
			`A sales team of clowns and pedophiles.`,
			`a slightly used tampon`,
			`A smiling bro with a glistening cock.`,
			`A Soft Pink Hole`,
			`A spontaneous musical number.`,
			`a squeeze of the hand`,
			`A surprisingly low amount of prison rape.`,
			`A sweet spaceship.`,
			`A swift hoog to the face.`,
			`A vagina that tastes like the bathroom floors at Tom's Diner.`,
			`A wedding reception. Again.`,
			`Actually giving a shit`,
			`All my gentleman suitors.`,
			`all pants are half off today`,
			`an all-you-can-eat pussy buffet`,
			`An Army of smack heads with HIV infected needles.`,
			`An ass like two football helmets.`,
			`An Etsy steampunk strap-on.`,
			`An Evening with Michael Buble.`,
			`An Ex-Porn Star Kindergarten Teacher`,
			`An unhinged Ferris wheel rolling toward the sea.`,
			`An unhinged Ferris wheel rolling toward the sea.`,
			`An unsurprising rash.`,
			`Andrew Hore Clubbing Seals`,
			`Another surprising Osprey crash.`,
			`Basic trainees.`,
			`Being a clever little girl.`,
			`Being a dumb ox.`,
			`Being a know-it-all.`,
			`Being back-to-back World War Champions!`,
			`Being blamed for things I didn't do.`,
			`Being fat from noodles.`,
			`Being wholly unimpressed`,
			`Big bad mama nipples.`,
			`Big Blue.`,
			`Big ol' floppy titties.`,
			`Bill Clinton.`,
			`Blood fisting`,
			`Blowing Stacks at The Kiddy Arcade`,
			`Born again virgins.`,
			`Bosveld lapa porn.`,
			`Bullshitting my ass off.`,
			`Buying the right toothbrush cup for my lifestyle.`,
			`Catch all this shit rolling down hill.`,
			`Chugging down a bucket of giraffe cum.`,
			`Clarke Gayford's fishing show`,
			`Clenching as you anticipate their inadvertent thrust into the wrong hole`,
			`Cockasaurus rex: the horniest dinosaur of them all.`,
			`Consent.`,
			`Converting your sex dungeon into a baby room`,
			`Crabs`,
			`Crushing on a lunch lady.`,
			`Crying kids in Church.`,
			`Cumming Hard`,
			`Dad's hemorroid pad`,
			`Daddy's credit card.`,
			`Death by teddy bear.`,
			`deformities floundering in seas of blood and blue paint`,
			`Demons and shit.`,
			`Dining with cardboard cutouts of the cast of Friends.`,
			`Dinner at a fine restaurant with candlelight, small portions, tablecloths, and a remote-controlled bullet in your partner.*`,
			`Disco Inferno.`,
			`Doritos and a Fruit Roll-Up.`,
			`Double rainbows.`,
			`Drinking my bro's pee-pee right out of his peen.`,
			`Drinking the tears of cancer patients.`,
			`Dying but miraculously getting brought back to life.`,
			`Eating an entire box of chocolates.`,
			`Eating too many Cinnabons and then vomiting and then eating the vomit.`,
			`Emotional baggage.`,
			`Enough chocolate to drown in`,
			`Exorcism.`,
			`Face Sitting`,
			`Fetish parties`,
			`Filling every pouch of a UtiliKilt™ with pizza.`,
			`Filling out preschool applications while still pregnant.`,
			`Finding your boat boo's slappy chokey bondage vid on Pornhub.`,
			`Fitting all your blongings into a seabag.`,
			`Flying saucers`,
			`Four hours of truly goofy sex with the Blue Man Group.`,
			`Fuck stains.`,
			`Gandalf's perfectly shaped eyebrows.`,
			`Gargling jizz.`,
			`Gay animals.`,
			`Generational wealth.`,
			`Genetically modified organisms`,
			`George Clooney's wife`,
			`Getting aborted.`,
			`Getting hit below the belt with a football`,
			`Getting your dick wet.`,
			`Glamping with Muammar Gaddafi.`,
			`Going around sniffing people's armpits.`,
			`Grandpa's bald spot.`,
			`Grassroots support`,
			`Having $57 in the bank.`,
			`Having a pint with Aquinas.`,
			`Having sex too soon after giving birth.`,
			`Having sloppy sex as your dog watches.`,
			`Hillary Clinton's death stare.`,
			`Hire that Stripper`,
			`Historically black colleges.`,
			`Hot brown piss.`,
			`Hot doooooooogs.`,
			`How bad my daughter fucked up her dance recital.`,
			`How wonderful it is when my master throws the ball and I go and get it for him.`,
			`Huge tits and a can-do attitude.`,
			`Indian burns.`,
			`Inserting a .50 cal round between your butt cheeks and squeezing.`,
			`intolerably vivid dreams`,
			`Jagerbombs`,
			`Jeff Price.`,
			`Jesus's death.`,
			`Jumping rope with a bunch of worms tied together.`,
			`Just the tip...........and the rest of the penis.`,
			`Kim Jong-un's barber.`,
			`Letting Gemma collins squirt on your face`,
			`Liam Neeson`,
			`Literally fucking the shit out of someone.`,
			`Living in a trashcan.`,
			`Living in an old rectory with other singles.`,
			`Lokking for your Dad's porn stash`,
			`Mad Stylin', yo.`,
			`Maintaining eye contact with a grown man while he takes a shit.`,
			`Making a list of people to kill.`,
			`Making shit up.`,
			`Making the printer work.`,
			`Masturbating in a robe like a rich person.`,
			`maximum effort, minimal gain`,
			`Mean people`,
			`Mediocre pizza`,
			`Mild racism and extreme homophobia`,
			`Mom's ability to take a cock.`,
			`Moon a Prime Minister.`,
			`Moral bankruptcy.`,
			`Muff Diving`,
			`multiple personality disorder`,
			`My father, who is a walrus.`,
			`My first kiss.`,
			`My magic awand`,
			`My mate Dave.`,
			`Neing trapped in the belly of a whale.`,
			`Not covering your mouth when you sneeze`,
			`Not having silly talk.`,
			`Nothing. Absolutely nothing.`,
			`Nuclear engineers.`,
			`Nunchucks.`,
			`on her left breast, a mole`,
			`One bottle of good wine and 3 bottles of blended garbage`,
			`One rude motherfucker`,
			`One titty hanging out.`,
			`Our mutual friend Brad.`,
			`Oversharing on social media`,
			`Powerful allergies`,
			`Preying that your spouse doesn't accidentally meet your boat boo at the commissary.`,
			`Pumpkin spice flavored condoms.`,
			`Putting Baby in a corner.`,
			`quick and easy, just the ways I like it`,
			`Racially biased employment equity questions.`,
			`Revenge gifting annoying toys`,
			`Reverse gentrification.`,
			`Richi McCaw; the PM we want, but will never deserve`,
			`Ripping off one company, who already ripped off another company, who stole the idea from another company.`,
			`Ripping out anal beads like you're starting a lawnmower.`,
			`Rising sea levels consistent with scientific predictions.`,
			`Role playing with moist towelettes.`,
			`Running naked through sprinklers.`,
			`Ryanair.`,
			`Sanctimommies`,
			`Sandwich.`,
			`Santa cumming down your chimney.`,
			`Saving 20% or more on khakis.`,
			`Screaming Orgasm`,
			`Scrotemeal.`,
			`Scrubbing under the folds.`,
			`Self-folding lundry.`,
			`sexual inadequacy`,
			`Sexual intercourse.`,
			`Shagging in a flak jacket`,
			`Shitting perfectly into a hot dog bun.`,
			`Shutting up so I can watch the game.`,
			`Sitting on a dick and sipping green tea.`,
			`Slapping Nigel Farage over and over.`,
			`SNES cartridge cleaning fluid.`,
			`Some douchebag yelling "More Cowbell."`,
			`Some kind of bullshit vegan burgoo.`,
			`Some really sticky Kentucky Durban.`,
			`Sorcery.`,
			`Special Olympics booing.`,
			`Spending my parent's hard-earned money.`,
			`Staring at a painting and going "hmmmmmm..."`,
			`statutory rape`,
			`Stockholm Syndrome`,
			`Subduing an officer using only the gentle touch of feminine hands.`,
			`Suddenly feeling really sad for 40 years.`,
			`Suicide Awareness Training.`,
			`Suicide bombers.`,
			`Susan, that bitch.`,
			`Swim naked in a bathtub full of tapioca pudding.`,
			`Syria's tired, poor, carefully profiled masses.`,
			`Taking a minute to really unpack what Shakespeare is getting at in this scene.`,
			`That awkward family who thinks it's "cybersex Monday."`,
			`The baby-industrial complex`,
			`The black vote.`,
			`The boogeyman.`,
			`The day the Mutant Ninja Turtles become adults`,
			`The EDL.`,
			`The entire Mormon Tabernacle Chior.`,
			`The Flying Spaghetti Monster.`,
			`the four,
or the three,
or the two`,
			`The gun lobby`,
			`The harsh light of day.`,
			`The harsh reality that all horses are people in horse costumes.`,
			`The hidden dick in your favorite Disney movie.`,
			`The hospital baby swap.`,
			`The Human Centipede: infinity edition.`,
			`The Large Hard-On Collider.`,
			`The lingering scent of gardenias.`,
			`The mere concept of Waco.`,
			`The milk that comes out of a person.`,
			`The mixture of fluids in my underwear right now.`,
			`The moment Sharon realized she married Steve.`,
			`The new Sheriff Joe Arpaio $20 bill.`,
			`The opioid epidemic.`,
			`The people of Florida.`,
			`The Prince of Egypt.`,
			`The psychological damage caused to women who believe "Twilight" demonstrates a healthy relationship.`,
			`The quickly fading dream of a quarter-acre section`,
			`The shame and regret of a prostate-triggered orgasm.`,
			`The systematic disenfranchisement of black voters.`,
			`The thing I'm hiding in my basement.`,
			`the touch-hole`,
			`The weaker sex.`,
			`The wrath of Vladimir Putin.`,
			`Three pounds of horse meat`,
			`Tiny terrorists`,
			`Tongueing a balloon knot arsehole`,
			`Tripping elderly roller skaters.`,
			`Unlocking a new sex position.`,
			`Velociraptor attacks`,
			`Vietnamese mercenaries hunting John Kerry.`,
			`Vomiting seafood and bleeding anally.`,
			`Walking in on your mom dominating your dad.`,
			`Warmongering.`,
			`Wear lip gloss on my anus.`,
			`Wearing Blues under your Klan robe.`,
			`Wet butt.`,
			`Whining until you get your way.`,
			`Whipping it out, with force.`,
			`White privilege.`,
			`Words.`,
			`Zig-zaggedy shrapnel scars.`,
		},
	}

	AddPack(pack)
}
