package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "PAX Prime 2015",
		Description: "Official PAX Prime 2015 convention pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `PAX Prime 2015 was incredible because of %s.`},
			&PromptCard{Prompt: `What was the hottest gaming trend at PAX?`},
			&PromptCard{Prompt: `I spent most of my PAX time %s.`},
			&PromptCard{Prompt: `The most memorable moment at PAX Prime 2015 was when %s.`},
			&PromptCard{Prompt: `I waited in line for PAX to get a chance to %s.`},
			&PromptCard{Prompt: `What's the dorkiest thing you did at PAX?`},
		},
		Responses: []ResponseCard{
			`A packed schedule`,
			`A packed house`,
			`A packing foam`,
			`A packing tape`,
			`A packing list`,
			`A packing material`,
			`A packing slip`,
			`A packhorse`,
			`A packing heat`,
			`A packing it in`,
			`A packing up and leaving`,
			`A packing strategy`,
			`A packing efficiency`,
			`A packing cubes`,
			`A packing tape dispenser`,
			`A packing supplies`,
			`A packing service`,
			`A packing industry`,
			`A packing plant`,
			`A packing warehouse`,
			`A packing facility`,
			`A packing company`,
			`A packing department`,
			`A packing division`,
			`A packing operation`,
			`A packing process`,
			`A packing line`,
			`A packing station`,
			`A packing area`,
			`A packing room`,
			`A packing center`,
			`A packing hub`,
			`A packing depot`,
			`A packing dock`,
			`A packing platform`,
			`A packing surface`,
			`A packing table`,
			`A packing bench`,
			`A packing counter`,
			`A packing desk`,
			`A packing stand`,
			`A packing unit`,
			`A packing module`,
			`A packing system`,
			`A packing network`,
			`A packing arrangement`,
			`A packing configuration`,
			`A packing setup`,
			`A packing layout`,
			`A packing structure`,
		},
	}
	AddPack(pack)
}
