package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Sports Pack",
		Description: "Sports and athletics themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The championship game was decided by %s.`},
			&PromptCard{Prompt: `In sports, there's nothing like %s.`},
			&PromptCard{Prompt: `The athlete's secret to success is %s.`},
			&PromptCard{Prompt: `The coach was legendary for %s.`},
			&PromptCard{Prompt: `The most controversial call in sports was when the referee %s.`},
			&PromptCard{Prompt: `What's the most unsporting thing you can do?`},
		},
		Responses: []ResponseCard{
			`A last-second goal`,
			`An impossible catch`,
			`A controversial call`,
			`A record-breaking performance`,
			`An upset victory`,
			`Perfect technique`,
			`Superhuman athleticism`,
			`Years of training`,
			`Mental toughness`,
			`Teamwork`,
			`Strategy and tactics`,
			`Home field advantage`,
			`A lucky bounce`,
			`Drugs and steroids`,
			`Illegal equipment`,
			`Bribing the referee`,
			`Playing dirty`,
			`Trash talk`,
			`A head butt`,
			`A sucker punch`,
			`An elbow to the face`,
			`A vicious tackle`,
			`A high stick`,
			`A low blow`,
			`Spitting on an opponent`,
			`Pulling a jersey`,
			`A false start`,
			`A foul play`,
			`An unsporting conduct`,
			`A time-out violation`,
			`An illegal formation`,
			`A holding penalty`,
			`An interference call`,
			`A traveling violation`,
			`A walking violation`,
			`A double dribble`,
			`A traveling call`,
			`A flagrant foul`,
			`A technical foul`,
			`An ejection from the game`,
		},
	}
	AddPack(pack)
}
