package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Gen Con 2018",
		Description: "Gen Con 2018 exclusive promo cards",
		Prompts: []*PromptCard{
			{Prompt: "What will Gen Con be remembered for in 2018?", NumPick: 1},
			{Prompt: "After 50 years, Gen Con is still the best place to find _.", NumPick: 1},
			{Prompt: "The new D&D module features a dungeon filled with _.", NumPick: 1},
			{Prompt: "At Gen Con, the best part of the experience is _.", NumPick: 1},
			{Prompt: "This year's surprise announcement from Magic: The Gathering: _.", NumPick: 1},
			{Prompt: "The cosplay contest winner dressed as _.", NumPick: 1},
		},
		Responses: []ResponseCard{
			"A massive board game tournament.",
			"A new tabletop RPG system.",
			"A unprecedented crowd size.",
			"Authentic medieval reproduction armor.",
			"Bedazzled chainmail bikinis.",
			"Blockchain-based trading cards.",
			"Breathtaking cosplay.",
			"Bustling vendor halls.",
			"Collectible miniatures.",
			"Comic book exclusives.",
			"Corporate sponsorship deals.",
			"Crowded hotel elevators.",
			"Crushing convention debt.",
			"D&D Beyond integration.",
			"Dehydration and poor hygiene.",
			"Derek the Depressed Orc.",
			"Desperate attempts to acquire limited edition merchandise.",
			"Desperately trying to find a bathroom.",
			"Disappointingly short celebrity panels.",
			"Discord among the gaming community.",
			"Discontinued game lines.",
			"Documented gatekeeping.",
			"Dollar signs in the organizers' eyes.",
			"Dorky pickup lines.",
			"Drinking problems.",
			"Each passing year's nostalgia.",
			"Elaborate costume fails.",
			"Embarrassing photos on the internet.",
			"Ensconced in gaming culture.",
			"Escalating entry fees.",
			"Escaping reality into fantasy worlds.",
			"Every gaming nerd's dream.",
			"Everyone cosplaying as the same character.",
			"Everything being sold out by Friday.",
			"Everything costing 300% more than retail.",
			"Everything wrong with mainstream gaming.",
			"Exclusive first looks at upcoming games.",
			"Exhausted volunteers.",
			"Expensive limited edition prints.",
			"Expensive loot boxes.",
			"Experiencing life-altering panic attacks.",
			"Fake props with suspiciously realistic details.",
			"Finding someone who gets your obscure hobby.",
			"Finding your tribe.",
			"First appearances of celebrity guests.",
			"First printings of limited cards.",
			"Forgetting to eat or drink anything.",
			"Free swag.",
			"Friendly competition.",
			"Friendly games turning into competitive nightmares.",
			"Friendly strangers becoming lifelong friends.",
			"Full-contact lightsaber duels.",
			"Functioning alcoholics.",
			"Fun and games (literally).",
			"Funko Pop collecting addictions.",
			"Gaming convention smell.",
			"Gaming conventions are the new comic cons.",
			"Gaming culture.",
			"Gaming in a warehouse.",
			"Gaming nerds.",
			"Gaming the system.",
			"Geek culture gone mainstream.",
			"Geek pride.",
			"Getting absolutely hammered at the hotel bar.",
			"Getting home on Sunday morning and realizing you need a vacation.",
			"Getting recognition for your fandom.",
			"Getting too drunk and hitting on someone's girlfriend.",
			"Getting your bearings in the massive hall.",
			"Giant board games.",
			"Giveaways and door prizes.",
			"Glorious days of gaming.",
			"Gold-pressed latinum (Deep Space Nine references).",
			"Good company and great games.",
			"Grand larceny in the dealer's hall.",
			"Great gaming moments that will last a lifetime.",
			"Great gaming with friends.",
			"Greedy game manufacturers.",
			"Greedy resellers.",
			"Grinding through tournament brackets.",
			"Growing communities.",
			"Growth of esports.",
			"Grudge matches between longtime rivals.",
			"Guaranteed good times.",
			"Guild wars and petty squabbles.",
			"Guinea pigs for untested game mechanics.",
			"Gumbo.",
			"Gutsy cosplayers.",
			"Guys who were way too into Magic.",
			"Guys with swords who take themselves too seriously.",
			"Hand-crafted dice.",
			"Handmade props.",
			"Handmade weapons that look disturbingly realistic.",
			"Happy crowds.",
			"Hardly sleeping for 72 hours.",
			"Harsh judgment of other people's gaming choices.",
			"Head-to-head gaming.",
			"Heart palpitations from too much caffeine.",
			"Heat exhaustion.",
			"Heavy bags full of swag.",
			"Hench cosplayers.",
			"Hentai vendors.",
			"Heralding the next big gaming trend.",
			"Here today, gone tomorrow fads.",
			"Heritage of gaming.",
			"Heroic tales.",
			"Hidden gems.",
			"High admission prices.",
			"High scores.",
			"High stakes games.",
			"High turnout.",
			"Highlights of the gaming year.",
			"Hinting that the rules are more like guidelines.",
			"Hip hop and board games.",
			"Hit games from previous Gen Cons.",
			"Hitting rock bottom and buying your third Kickstarter that year.",
			"Hoarding limited edition cards.",
			"Hobby becoming a lifestyle.",
			"Hobby shop recommendations.",
			"Hobbyist vs. competitive gamers.",
			"Holding onto your bag of swag for dear life.",
			"Holding your own in a tournament.",
			"Holiday shopping ideas.",
			"Home invasions (metaphorical).",
			"Homebrewed supplements.",
			"Homegrown gaming companies.",
			"Honestly, I don't remember the last 6 hours.",
			"Honestly, we're not sure what this game is either.",
			"Hopeful Kickstarter campaigns.",
			"Hopeful new game designers.",
			"Hoping to see a celebrity.",
			"Hoping to win big at the tables.",
			"Hoping you never run into that one player again.",
			"Hopscotch.",
			"Horizontal negotiations.",
			"Horror and giggles.",
			"Horror of forgetting your hotel room key.",
			"Horror of losing your badge.",
			"Horror of losing your gaming group.",
			"Horror of spending $200 on a single game.",
			"Horror of your ex being at the convention.",
			"Horror-themed board games.",
			"Horse stance.",
			"Hot beverages.",
			"Hot dogs.",
			"Hot girls cosplaying.",
			"Hot guys cosplaying.",
			"Hot takes on the current meta.",
			"Hot topic models.",
			"Hot topic.",
			"Hotch.",
			"Hotel hijinks.",
			"Hotel room parties.",
			"Hotel rooms packed with random strangers.",
			"Hothouse of creativity.",
			"Hotly contested matches.",
			"Hotly debated rules interpretations.",
			"Hotseat moments.",
			"Hotselling games.",
			"Hotshot designers.",
			"Hotspotting.",
			"Hotspot venues.",
			"Hotstuff.",
			"Hottest games of 2018.",
			"Hotwire.",
			"Hotwireq.",
			"Hotwiring interest in your indie game.",
			"Hound dogs and board games.",
			"Hounded by game companies for feedback.",
			"Hourglass moments.",
			"House rules.",
			"House rules turning friendly games into bloodbaths.",
			"Housing crisis roleplay scenarios.",
			"Housing poor gamers.",
			"Housekeeping staff who hate conventions.",
			"How did we lose 16 hours?",
			"How did we lose another $300?",
			"How did we lose so much blood?",
			"How did we lose so much sleep?",
			"How do you even begin to describe this experience?",
			"How do you make money running a gaming convention?",
			"How do you say 'I'm a total geek' without saying it?",
			"How do you spell 'addiction'?",
			"How gaming changed my life.",
			"How I became a better person through gaming.",
			"How I became a better person through gaming (lie).",
			"How I became a gaming addict.",
			"How I became a laughingstock.",
			"How I became a tabletop gamer.",
			"How I became a worse person through gaming.",
			"How I ended up married to someone I met at a convention.",
			"How I met your mother (through World of Warcraft).",
			"How I met your mother (via Gen Con).",
			"How I spent my student loan money.",
			"How I spent my year's salary.",
			"How I spent my year's vacation days.",
			"How I wasted an entire weekend.",
			"How much would you pay for a one-of-a-kind gaming experience?",
			"How to find your gaming tribe.",
			"How to get better at your favorite game.",
			"How to lose friends and alienate people.",
			"How to lose money at a convention.",
			"How to make new friends at Gen Con.",
			"How to survive 72 hours without sleep.",
			"How to survive on Red Bull alone.",
			"How to turn your hobby into bankruptcy.",
			"How we made it through the weekend.",
			"Howard and Sheldon were right.",
			"However, if I had to pick just one thing...",
		},
	}
	AddPack(pack)
}
