package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "superhero",
		Description: "Superhero and comic book themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `Every superhero's secret weakness is %s.`},
			&PromptCard{Prompt: `The real superpower is %s.`},
			&PromptCard{Prompt: `If I were a superhero, I would fight %s.`},
			&PromptCard{Prompt: `Batman would never use %s in his utility belt.`},
			&PromptCard{Prompt: `The villain's master plan was to destroy %s.`},
			&PromptCard{Prompt: `What would give you superpowers?`},
		},
		Responses: []ResponseCard{
			`A radioactive isotope`,
			`Gamma rays`,
			`Spider bite`,
			`Kryptonite`,
			`A power ring`,
			`A magic hammer`,
			`Super strength`,
			`Super speed`,
			`Flight`,
			`Invisibility`,
			`Telepathy`,
			`Shape-shifting`,
			`Regeneration`,
			`Invulnerability`,
			`A healing factor`,
			`Superhuman durability`,
			`Enhanced reflexes`,
			`Mastery of technology`,
			`Genius intellect`,
			`Mastery of martial arts`,
			`Wealth and resources`,
			`A secret base`,
			`High-tech gadgets`,
			`Advanced armor`,
			`A secret identity`,
			`A trusty sidekick`,
			`A loyal butler`,
			`A superhero team`,
			`A Justice League roster`,
			`A league of their own`,
			`A rogues gallery`,
			`A superhero franchise`,
			`A comic book series`,
			`A movie deal`,
			`A merchandising empire`,
			`A franchise reboot`,
			`A crossover event`,
			`An origin story`,
			`A tragic backstory`,
			`A triumph of good over evil`,
		},
	}
	AddPack(pack)
}
