package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "cats-musical",
		Description: "Cards inspired by the musical CATS",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `CATS the musical is best described as %s.`},
			&PromptCard{Prompt: `Jellicle cats are known for %s.`},
			&PromptCard{Prompt: `The most important thing to a cat is %s.`},
			&PromptCard{Prompt: `The Jellicle Ball is a celebration of %s.`},
			&PromptCard{Prompt: `Memory is a %s.`},
			&PromptCard{Prompt: `Every cat's dream is to reach %s.`},
		},
		Responses: []ResponseCard{
			`Elaborate cat makeup`,
			`Dancer in a leotard`,
			`Incomprehensible storyline`,
			`Inexplicable costumes`,
			`A fog machine`,
			`Andrew Lloyd Webber`,
			`The Rum Tum Tugger`,
			`Mysterious choreography`,
			`Tail-centered movement`,
			`Feline gymnastics`,
			`Hypnotic repetition`,
			`A cult classic`,
			`Pure chaos`,
			`Interpretive dance`,
			`Sensory overload`,
			`A fever dream`,
			`Peak theater`,
			`Something precious`,
			`A fleeting memory`,
			`Bittersweet nostalgia`,
			`The unknown`,
			`The Heaviside Layer`,
			`Redemption`,
			`Eternal rebirth`,
			`The light above`,
			`A second chance`,
			`Transcendence`,
			`Transformation`,
			`Mystery and wonder`,
			`Ancient wisdom`,
			`Feline spirituality`,
			`Urban legend`,
			`A fever dream`,
			`Nightmares in leotards`,
			`Bewilderment`,
			`Confusion and awe`,
			`Musical theater gone wrong`,
			`An experience nobody asked for`,
			`A cautionary tale`,
			`Proof that anything can be a musical`,
		},
	}
	AddPack(pack)
}
