package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Horror Pack",
		Description: "Horror and scary themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `In a horror movie, %s always shows up at the worst time.`},
			&PromptCard{Prompt: `The scariest thing about %s is that it's %s.`},
			&PromptCard{Prompt: `Nobody survives when %s happens.`},
			&PromptCard{Prompt: `The best hiding place during %s is %s.`},
			&PromptCard{Prompt: `The zombie apocalypse started because of %s.`},
			&PromptCard{Prompt: `What would make a horror movie even scarier?`},
		},
		Responses: []ResponseCard{
			`Possessed dolls`,
			`Creepy crawlies`,
			`Demonic possession`,
			`Paranormal activity`,
			`Supernatural forces`,
			`Evil spirits`,
			`Poltergeists`,
			`Haunted houses`,
			`Cursed objects`,
			`Blood-soaked floors`,
			`A child's laughter in the dark`,
			`Unexplained noises`,
			`Missing persons`,
			`Mysterious murders`,
			`Ritualistic killings`,
			`Torture chambers`,
			`Cannibals`,
			`Werewolves`,
			`Vampires`,
			`Witches`,
			`Zombies`,
			`Mutants`,
			`Creatures from the deep`,
			`Alien invaders`,
			`Government experiments`,
			`Mad scientists`,
			`Angry mobs`,
			`Psycho killers`,
			`Masked murderers`,
			`Serial killers`,
			`The boogeyman`,
			`Ghosts of the past`,
			`Vengeful spirits`,
			`Soul-stealing entities`,
			`Interdimensional portals`,
			`Lovecraftian horrors`,
			`Eldritch abominations`,
			`Ancient curses`,
			`The descent into madness`,
			`Isolation and despair`,
		},
	}
	AddPack(pack)
}
