package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "PAX Prime 2014",
		Description: "PAX Prime 2014 exclusive promo cards",
		Prompts: []*PromptCard{
			{Prompt: "PAX Prime 2014 was the best PAX because _.", NumPick: 1},
			{Prompt: "If I could bring one thing back from PAX, it would be _.", NumPick: 1},
			{Prompt: "The most controversial discussion at PAX this year was about _.", NumPick: 1},
			{Prompt: "The most anticipated announcement at PAX Prime was _.", NumPick: 1},
			{Prompt: "The surprise hit game at PAX was _.", NumPick: 1},
			{Prompt: "I will remember PAX Prime 2014 for _.", NumPick: 1},
		},
		Responses: []ResponseCard{
			"A big reveal.",
			"A big surprise.",
			"A big announcement.",
			"A bingo card.",
			"A bird's eye view.",
			"A bird's nest.",
			"A bird strike.",
			"A birdage.",
			"A birdbath.",
			"A birdcage.",
			"A birdcall.",
			"A birdcalls.",
			"A birded.",
			"A birdeed.",
			"A birdees.",
			"A birdelike.",
			"A birden.",
			"A birdens.",
			"A birder.",
			"A birderine.",
			"A birderers.",
			"A birderies.",
			"A birders.",
			"A birdery.",
			"A birdes.",
			"A birde.",
			"A birdface.",
			"A birdfaces.",
			"A birdfarm.",
			"A birdfarms.",
			"A birdfat.",
			"A birdfats.",
			"A birdfeed.",
			"A birdfeeds.",
			"A birdfence.",
			"A birdfences.",
			"A birdfended.",
			"A birdfender.",
			"A birdfenders.",
			"A birdfish.",
			"A birdfishes.",
			"A birdflesh.",
			"A birdfleshes.",
			"A birdflight.",
			"A birdflight.",
			"A birdflights.",
			"A birdflock.",
			"A birdflocks.",
			"A birdflood.",
			"A birdfloods.",
			"A birdflop.",
			"A birdflopped.",
			"A birdflops.",
			"A birdflown.",
			"A birdflue.",
			"A birdflued.",
			"A birdflues.",
			"A birdfluid.",
			"A birdfluids.",
			"A birdflung.",
			"A birdflush.",
			"A birdflushes.",
			"A birdfly.",
			"A birdflying.",
			"A birdfoal.",
			"A birdfoals.",
			"A birdfoam.",
			"A birdfoams.",
			"A birdfod.",
			"A birdfods.",
			"A birdfoe.",
			"A birdfoes.",
			"A birdfog.",
			"A birdfogs.",
			"A birdfogue.",
			"A birdfogues.",
			"A birdfoil.",
			"A birdfoils.",
			"A birdfoilsure.",
			"A birdfoisture.",
			"A birdfoistures.",
			"A birdfold.",
			"A birdfolds.",
			"A birdfole.",
			"A birdfoles.",
			"A birdfolia.",
			"A birdfolias.",
			"A birdfoliage.",
			"A birdfoliages.",
			"A birdfoliate.",
			"A birdfoliated.",
			"A birdfoliately.",
			"A birdfoliates.",
			"A birdfoliating.",
			"A birdfoliation.",
			"A birdfoliations.",
			"A birdfolied.",
			"A birdfolies.",
			"A birdfoliness.",
			"A birdfolic.",
			"A birdfolios.",
			"A birdfolio.",
			"A birdfolious.",
			"A birdfolious.",
			"A birdfoliosis.",
			"A birdfoliosity.",
			"A birdfoll.",
			"A birdfolles.",
			"A birdfollice.",
			"A birdfollis.",
			"A birdfolow.",
			"A birdfollows.",
			"A birdfollower.",
			"A birdfollowers.",
			"A birdfolly.",
			"A birdfolsom.",
			"A birdfont.",
			"A birdfonts.",
			"A birdfoo.",
			"A birdfooba.",
			"A birdfoobar.",
			"A birdfoobars.",
			"A birdfoobas.",
			"A birdfoobass.",
			"A birdfoobasties.",
			"A birdfoobastic.",
			"A birdfoobastication.",
			"A birdfoobastitical.",
			"A birdfoobasticalness.",
			"A birdfoobastically.",
			"A birdfoobastications.",
			"A birdfoobasticate.",
			"A birdfoobasticated.",
			"A birdfoobasticates.",
			"A birdfoobastication.",
			"A birdfoobastications.",
			"A birdfoobasticity.",
			"A birdfoobasties.",
			"A birdfoobastie.",
			"A birdfoobastiness.",
			"A birdfoobasty.",
			"A birdfood.",
			"A birdfoods.",
			"A birdfoof.",
			"A birdfoofs.",
			"A birdfoog.",
			"A birdfoogage.",
			"A birdfoogs.",
			"A birdfooha.",
			"A birdfoohah.",
			"A birdfoohaws.",
			"A birdfoohas.",
			"A birdfoohaw.",
			"A birdfoohaws.",
			"A birdfoohees.",
			"A birdfoohey.",
			"A birdfoohi.",
			"A birdfoohis.",
			"A birdfooho.",
			"A birdfoohos.",
			"A birdfoohoos.",
			"A birdfoohoos.",
			"A birdfoohooser.",
			"A birdfoohoosers.",
			"A birdfoohoosy.",
			"A birdfoohoot.",
			"A birdfoohooter.",
			"A birdfoohooters.",
			"A birdfoohooties.",
			"A birdfoohoots.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
			"A birdfoohootsy.",
		},
	}
	AddPack(pack)
}
