package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "alcohol",
		Description: "Alcohol and drinking themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The best drink to order at a bar is %s.`},
			&PromptCard{Prompt: `A night of drinking should never include %s.`},
			&PromptCard{Prompt: `The worst hangover of my life was caused by %s.`},
			&PromptCard{Prompt: `The key to a good party is %s.`},
			&PromptCard{Prompt: `I've made the worst decisions while %s.`},
			&PromptCard{Prompt: `What's the best thing about getting drunk?`},
		},
		Responses: []ResponseCard{
			`Beer`,
			`Wine`,
			`Whiskey`,
			`Vodka`,
			`Tequila`,
			`Rum`,
			`Gin`,
			`Brandy`,
			`Cognac`,
			`Champagne`,
			`Prosecco`,
			`Mixed drinks`,
			`Cocktails`,
			`Shots`,
			`A cold beer`,
			`A hot toddy`,
			`A margarita`,
			`A cosmopolitan`,
			`A mojito`,
			`A daiquiri`,
			`A piña colada`,
			`A Long Island Iced Tea`,
			`A bloody mary`,
			`A mimosa`,
			`A beer pong match`,
			`Keg stands`,
			`Chugging contests`,
			`Beer bonging`,
			`Funneling`,
			`Downing shots`,
			`Bar hopping`,
			`A pub crawl`,
			`A house party`,
			`A college party`,
			`A bachelor party`,
			`A bachelorette party`,
			`A karaoke night`,
			`Drunk karaoke`,
			`Drunk dancing`,
			`Drunk texting`,
		},
	}
	AddPack(pack)
}
