package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "History Pack",
		Description: "History and historical events themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The most significant moment in history was %s.`},
			&PromptCard{Prompt: `If I could change one thing about history, it would be %s.`},
			&PromptCard{Prompt: `The greatest person in history was %s.`},
			&PromptCard{Prompt: `Historical figures are remembered for %s.`},
			&PromptCard{Prompt: `The turning point of %s was when %s.`},
			&PromptCard{Prompt: `What secret would change history forever?`},
		},
		Responses: []ResponseCard{
			`The invention of the wheel`,
			`The discovery of fire`,
			`The agricultural revolution`,
			`The industrial revolution`,
			`The printing press`,
			`The steam engine`,
			`Electricity`,
			`The internet`,
			`The Renaissance`,
			`The Enlightenment`,
			`The American Revolution`,
			`The French Revolution`,
			`World War I`,
			`World War II`,
			`The Cold War`,
			`The moon landing`,
			`The fall of the Berlin Wall`,
			`The civil rights movement`,
			`Women's suffrage`,
			`The abolition of slavery`,
			`The signing of the Magna Carta`,
			`The Declaration of Independence`,
			`The Constitution`,
			`The Louisiana Purchase`,
			`The Emancipation Proclamation`,
			`The invention of the lightbulb`,
			`The discovery of antibiotics`,
			`The split of the atom`,
			`The theory of evolution`,
			`The theory of relativity`,
			`The scientific method`,
			`The Age of Exploration`,
			`The Spanish Inquisition`,
			`The Dark Ages`,
			`The Medieval Times`,
			`The Victorian Era`,
			`The Jazz Age`,
			`The Great Depression`,
			`The invention of democracy`,
			`The invention of philosophy`,
		},
	}
	AddPack(pack)
}
