package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "love",
		Description: "Love and romance themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `True love is %s.`},
			&PromptCard{Prompt: `For our anniversary, I got my partner %s.`},
			&PromptCard{Prompt: `Nothing says romance like %s.`},
			&PromptCard{Prompt: `The worst thing to say on a first date is %s.`},
			&PromptCard{Prompt: `My ideal romantic getaway involves %s.`},
			&PromptCard{Prompt: `When it comes to love, %s is overrated.`},
		},
		Responses: []ResponseCard{
			`A rose by any other name`,
			`A diamond ring`,
			`Flowers and chocolates`,
			`A candlelit dinner`,
			`A sunset walk`,
			`Holding hands`,
			`A kiss`,
			`An embrace`,
			`Whispered sweet nothings`,
			`A love letter`,
			`A romantic poem`,
			`Sharing a meal`,
			`A slow dance`,
			`A moonlit night`,
			`A shooting star`,
			`Matching tattoos`,
			`A couple's vacation`,
			`A honeymoon`,
			`A wedding ring`,
			`"I love you"`,
			`Unconditional devotion`,
			`A soulmate`,
			`Destiny`,
			`Fate`,
			`Chemistry`,
			`Passion`,
			`Intimacy`,
			`Trust`,
			`Commitment`,
			`Loyalty`,
			`Understanding`,
			`Compromise`,
			`Forgiveness`,
			`Sacrifice`,
			`Honesty`,
			`Communication`,
			`Respect`,
			`Admiration`,
			`Affection`,
			`Tenderness`,
		},
	}
	AddPack(pack)
}
