package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "animals-pack",
		Description: "Animals and wildlife themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `If animals could talk, they would complain about %s.`},
			&PromptCard{Prompt: `The most dangerous animal is %s.`},
			&PromptCard{Prompt: `My favorite animal is %s because of %s.`},
			&PromptCard{Prompt: `In the wild, %s is the apex predator.`},
			&PromptCard{Prompt: `The most interesting animal behavior is %s.`},
			&PromptCard{Prompt: `What would be the coolest animal to be?`},
		},
		Responses: []ResponseCard{
			`Lions`,
			`Tigers`,
			`Bears`,
			`Wolves`,
			`Sharks`,
			`Crocodiles`,
			`Snakes`,
			`Scorpions`,
			`Spiders`,
			`Eagles`,
			`Hawks`,
			`Owls`,
			`Elephants`,
			`Rhinos`,
			`Hippos`,
			`Gorillas`,
			`Chimpanzees`,
			`Orangutans`,
			`Dolphins`,
			`Whales`,
			`Octopuses`,
			`Jaguars`,
			`Panthers`,
			`Pumas`,
			`Leopards`,
			`Cheetahs`,
			`Hyenas`,
			`Wild dogs`,
			`Anacondas`,
			`Pythons`,
			`Komodo dragons`,
			`Tarantulas`,
			`Venomous creatures`,
			`Poisonous frogs`,
			`Venomous snakes`,
			`Stinging rays`,
			`Box jellyfish`,
			`Piranhas`,
			`Moose`,
			`Gorillas`,
		},
	}
	AddPack(pack)
}
