package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "PAX Prime 2010",
		Description: "Official PAX Prime 2010 convention pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `At the gaming convention, I discovered that %s.`},
			&PromptCard{Prompt: `The best part of PAX Prime 2010 was %s.`},
			&PromptCard{Prompt: `I got in line for 3 hours to see %s.`},
			&PromptCard{Prompt: `What brought the most shame to the gaming community?`},
			&PromptCard{Prompt: `The gaming community was shocked to find out that %s.`},
			&PromptCard{Prompt: `At PAX, I saw a grown man %s.`},
		},
		Responses: []ResponseCard{
			`A sealed deck`,
			`A sense of adventure`,
			`A sense of belonging`,
			`A sense of community`,
			`A sense of dread`,
			`A sense of humor`,
			`A sense of purpose`,
			`A sense of shame`,
			`A sense of wonder`,
			`A senseless act`,
			`A sensitive issue`,
			`A sensual experience`,
			`A sentiment`,
			`A sentimental journey`,
			`A sentient AI`,
			`A sentient being`,
			`A sentient cloud`,
			`A sentient toilet`,
			`A sentient weapon`,
			`A sentry`,
			`A separation`,
			`A separate peace`,
			`A separate but equal`,
			`A separatism`,
			`A separatist`,
			`A separator`,
			`A sephardic jew`,
			`A sepia tone`,
			`A seppuku`,
			`A september`,
			`A septet`,
			`A septic tank`,
			`A septic shock`,
			`A septicemia`,
			`A septillion`,
			`A septuple`,
			`A septuplet`,
			`A septum`,
			`A sepulcher`,
			`A sepulchral silence`,
			`A sepulchre`,
			`A sepulture`,
			`A sequel`,
			`A sequence`,
			`A sequencer`,
			`A sequencing`,
			`A sequent`,
			`A sequential logic`,
			`A sequester`,
			`A sequestered jury`,
			`A sequestrant`,
			`A sequestrate`,
			`A sequestration`,
			`A sequestrator`,
			`A sequestrum`,
			`A sequin`,
			`A sequined dress`,
			`A sequoia`,
			`A seraph`,
		},
	}
	AddPack(pack)
}
