package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "cah-fifth-expansion",
		Description: "CAH: Fifth Expansion",
		Prompts: []*PromptCard{
			{Prompt: "Check me out, yo! I call this dance move %s."},
			{Prompt: "Fun tip! When your man asks you to go down on him, try surprising him with %s instead."},
			{Prompt: "How did I lose my virginity?"},
			{Prompt: "I am become %s, destroyer of %s."},
			{Prompt: "In the beginning there was %s. And God said, \"Let there be %s.\""},
			{Prompt: "It's a trap! %s"},
			{Prompt: "Kids, Dad is going to be staying at a special hotel called %s for a while."},
			{Prompt: "Listen, Gary, I like you. But if you want that corner office, you're going to have to show me %s."},
			{Prompt: "My fellow Americans, before this decade is out, we will have %s on the moon!"},
			{Prompt: "My life is ruled by a vicious cycle of %s and %s."},
			{Prompt: "Next from J.K. Rowling: Harry Potter and the Chamber of %s."},
			{Prompt: "Next up on TNT: %s: the Story of %s."},
			{Prompt: "Science will never explain %s."},
			{Prompt: "Sorry everyone, I just %s."},
			{Prompt: "The Five Stages of Grief: denial, anger, bargaining, %s, acceptance."},
			{Prompt: "The healing process began when I joined a support group for victims of %s."},
			{Prompt: "The Japanese have developed a smaller, more efficient version of %s."},
			{Prompt: "This is your captain speaking. Fasten your seatbelts and prepare for %s."},
			{Prompt: "Today on Jerry Springer: \"Help! My son is %s!\""},
			{Prompt: "What killed my boner?"},
		},
		Responses: []ResponseCard{
			"10 Incredible Facts About the Anus.",
			"A bass drop so huge it tears the starry vault asunder to reveal the face of God.",
			"A bunch of idiots playing a card game instead of interacting like normal humans.",
			"A buttload of candy.",
			"A chimpanzee in sunglasses fucking your wife.",
			"A constant need for validation.",
			"A crazy little thing called love.",
			"A dance move that's just sex.",
			"A disappointing salad.",
			"A face full of horse cum.",
			"A fart.",
			"A gender identity that can only be conveyed through slam poetry.",
			"A giant powdery manbaby.",
			"A hopeless amount of spiders.",
			"A horse with no legs.",
			"A kiss on the lips.",
			"A Native American who solves crimes by going into the spirit world.",
			"A peyote-fueled vision quest.",
			"A pizza guy who fucked up.",
			"A possible Muslim.",
			"A reason not to commit suicide.",
			"A sex comet from Neptune that plunges the Earth into eternal sexiness.",
			"A sex goblin with a carnival penis.",
			"A shiny rock that proves I love you.",
			"A team of lawyers.",
			"A thrilling chase over the rooftops of Rio de Janeiro.",
			"A turd.",
			"A Ugandan warlord.",
			"A whole lotta woman.",
			"A whole new kind of porn.",
			"A woman.",
			"A zero-risk way to make $2,000 from home.",
			"Actual mutants with medical conditions and no superpowers.",
			"Africa.",
			"AIDS monkeys.",
			"All the single ladies.",
			"All these decorative pillows.",
			"Almost giving money to a homeless person.",
			"Ambiguous sarcasm.",
			"An inability to form meaningful relationships.",
			"An interracial handshake.",
			"An overwhelming variety of cheeses.",
			"An unforgettable quinceanera.",
			"An uninterrupted history of imperialism and exploitation.",
			"Anal fissures like you wouldn't believe.",
			"Ancient Athenian boy-fucking.",
			"Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of night.",
			"Ass to mouth.",
			"Backwards knees.",
			"Bathing in moonsblood and dancing around the ancient oak.",
			"Being a terrible mother.",
			"Being John Malkovich.",
			"Being nine years old.",
			"Being paralyzed from the neck down.",
			"Being popular and good at sports.",
			"Being worshipped as the one true God.",
			"Beloved television star Bill Cosby.",
			"Blackface.",
			"Blackula.",
			"Blowjobs for everyone.",
			"Bouncing up and down.",
			"Breastfeeding a ten year old.",
			"Cancer.",
			"Changing a person's mind with logic and facts.",
			"Child Protective Services.",
			"Child support payments.",
			"Cool, relatable cancer teens.",
			"Crazy opium eyes.",
			"Crippling social anxiety.",
			"Crying and shitting and eating spaghetti.",
			"Cute boys.",
			"Daddy's credit card.",
			"Deez nuts.",
			"Dem titties.",
			"Depression.",
			"Doing the right stuff to her nipples.",
			"Doo-doo.",
			"Drinking responsibly.",
			"Eating together like a god damn family for once.",
			"Eggs.",
			"Ejaculating inside another man's wife.",
			"Ejaculating live bees and the bees are angry.",
			"Ennui.",
			"Every ounce of charisma left in Mick Jagger's tired body.",
			"Exploding pigeons.",
			"Falling into the toilet.",
			"Figuring out how to have sex with a dolphin.",
			"Filling a man's anus with concrete.",
			"Finally finishing off the Indians.",
			"Free ice cream, yo.",
			"Fresh dill from the patio.",
			"Fucking a corpse back to life.",
			"Generally having no idea what's going on.",
			"Getting all offended.",
			"Getting caught by the police and going to jail.",
			"Getting down to business to defeat the Huns.",
			"Getting drive-by shot.",
			"Getting eaten alive by Guy Fieri.",
			"Getting shot out of a cannon.",
			"Giant sperm from outer space.",
			"Going down on a woman, discovering that her vagina is filled with eyeballs, and being totally into that.",
			"Going inside at some point because of the mosquitoes.",
			"Going to a high school reunion on ketamine.",
			"Growing up chained to a radiator in perpetual darkness.",
			"Having been dead for a while.",
			"How awesome I am.",
			"Immortality cream.",
			"Important news about Taylor Swift.",
			"Injecting speed into one arm and horse tranquilizer into the other.",
			"Interspecies marriage.",
			"Irrefutable evidence that God is real.",
			"Kale.",
			"Khakis.",
			"Like a million alligators.",
			"Lots and lots of abortions.",
			"Meaningless sex.",
			"Moderate-to-severe joint pain.",
			"Mom's new boyfriend.",
			"Morpheus.",
			"My boyfriend's stupid penis.",
			"My dad's dumb fucking face.",
			"My dead son's baseball glove.",
			"My first period.",
			"My worthless son.",
			"Neil Diamond's Greatest Hits.",
			"Never having sex again.",
			"No clothes on, penis in vagina.",
			"Not believing in giraffes.",
			"One unforgettable night of passion.",
			"Out-of-this-world bazongas.",
			"Owls, the perfect predator.",
			"P.F. Chang himself.",
			"Peeing into a girl's butt to make a baby.",
			"Potato.",
			"Prince Ali, fabulous he, Ali Ababwa.",
			"Pussy.",
			"Reading the entire End-User License Agreement.",
			"Ripping a dog in half.",
			"Robots who just want to party.",
			"Russian super-tuberculosis.",
			"Seeing my village burned and my family slaughtered before my eyes.",
			"Seeing things from Hitler's perspective.",
			"September 11th, 2001.",
			"Setting my balls on fire and cartwheeling to Ohio.",
			"Shapes and colors.",
			"Sharks with legs.",
			"Slowly easing down onto a cucumber.",
			"Smoking crack, for instance.",
			"Snorting coke off a clown's boner.",
			"Social justice warriors with flamethrowers of compassion.",
			"Some shit-hot guitar licks.",
			"Some sort of Asian.",
			"Sports.",
			"Storing a bunch of acorns in my pussy.",
			"Stuffing a child's face with Fun Dip® until he starts having fun.",
			"Stupid.",
			"Such a big boy.",
			"Sucking all the milk out of a yak.",
			"Sudden penis loss.",
			"Teaching a girl how to handjob the penis.",
			"Texas.",
			"The Abercrombie & Fitch lifestyle.",
			"The amount of gay I am.",
			"The basic suffering that pervades all of existence.",
			"The best taquito in the galaxy.",
			"The black half of Barack Obama.",
			"The color 'puce'.",
			"The complex geopolitical quagmire that is the Middle East.",
			"The dentist.",
			"The eight gay warlocks who dictate the rules of fashion.",
			"The eighth graders.",
			"The euphoric rush of strangling a drifter.",
			"The ghost of Marlon Brando.",
			"The haunting stare of an Iraqi child.",
			"The inability to form meaningful relationships.",
			"The male gaze.",
			"The passage of time.",
			"The peaceful and nonthreatening rise of China.",
			"The power of the Dark Side.",
			"The right amount of cocaine.",
			"The safe word.",
			"The secret formula for ultimate female satisfaction.",
			"The size of my penis.",
			"The sweet song of sword against sword and the braying of mighty war beasts.",
			"The swim team, all at once.",
			"The tiger that killed my father.",
			"The tiniest shred of evidence that God is real.",
			"The unbelievable world of mushrooms.",
			"The white half of Barack Obama.",
			"Three consecutive seconds of happiness.",
			"Throwing stones at a man until he dies.",
			"Too much cocaine.",
			"Total fucking chaos.",
			"Treasures beyond your wildest dreams.",
			"Turning the rivers red with the blood of infidels.",
			"Two whales fucking the shit out of each other.",
			"Unquestioning obedience.",
			"Unrelenting genital punishment.",
			"Unsheathing my massive horse cock.",
			"Vegetarian options.",
			"Walking into a glass door.",
			"Wearing glasses and sounding smart.",
			"Western standards of beauty.",
			"What Jesus would do.",
			"Whatever a McRib® is made of.",
			"Whatever you wish, mother.",
			"Whispering all sexy.",
		},
	}

	AddPack(pack)
}
