package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Second Expansion",
		Description: "CAH: Second Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s would be woefully incomplete without %s.`},
			&PromptCard{Prompt: `A remarkable new study has shown that chimps have evolved their own primitive version of %s.`},
			&PromptCard{Prompt: `After months of debate, the Occupy Wall Street General Assembly could only agree on "More %s!"`},
			&PromptCard{Prompt: `Before %s, all we had was %s.`},
			&PromptCard{Prompt: `Before I run for president, I must destroy all evidence of my involvement with %s.`},
			&PromptCard{Prompt: `Charades was ruined for me forever when my mom had to act out %s.`},
			&PromptCard{Prompt: `During his midlife crisis, my dad got really into %s.`},
			&PromptCard{Prompt: `Everyone down on the ground! We don't want to hurt anyone. We're just here for %s.`},
			&PromptCard{Prompt: `I spent my whole life working toward %s, only to have it ruined by %s.`},
			&PromptCard{Prompt: `I went from %s to %s, all thanks to %s.`},
			&PromptCard{Prompt: `If God didn't want us to enjoy %s, he wouldn't have given us %s.`},
			&PromptCard{Prompt: `In his newest and most difficult stunt, David Blaine must escape from %s.`},
			&PromptCard{Prompt: `Little Miss Muffet Sat on a tuffet, Eating her curds and %s.`},
			&PromptCard{Prompt: `Members of New York's social elite are paying thousands of dollars just to experience %s.`},
			&PromptCard{Prompt: `My country, 'tis of thee, sweet land of %s.`},
			&PromptCard{Prompt: `My mom freaked out when she looked at my browser history and found %s.com/%s.`},
			&PromptCard{Prompt: `My new favorite porn star is Joey "%s" McGee.`},
			&PromptCard{Prompt: `Next time on Dr. Phil: How to talk to your child about %s.`},
			&PromptCard{Prompt: `Only two things in life are certain: death and %s.`},
			&PromptCard{Prompt: `The Five Stages of Grief: denial, anger, bargaining, %s, acceptance.`},
			&PromptCard{Prompt: `The healing process began when I joined a support group for victims of %s.`},
			&PromptCard{Prompt: `The votes are in, and the new high school mascot is %s.`},
			&PromptCard{Prompt: `This is your captain speaking. Fasten your seatbelts and prepare for %s.`},
			&PromptCard{Prompt: `This month's Cosmo: "Spice up your sex life by bringing %s into the bedroom."`},
			&PromptCard{Prompt: `Tonight on 20/20: What you don't know about %s could kill you.`},
			&PromptCard{Prompt: `What's harshing my mellow, man?`},
			&PromptCard{Prompt: `You haven't truly lived until you've experienced %s and %s at the same time.`},
			&PromptCard{Prompt: `Your persistence is admirable, my dear Prince. But you cannot win my heart with %s alone.`},
		},

		Responses: []ResponseCard{
			`A 55-gallon drum of lube.`,
			`A bigger, blacker dick.`,
			`A Burmese tiger pit.`,
			`A dollop of sour cream.`,
			`A fortuitous turnip harvest.`,
			`A magic hippie love cloud.`,
			`A man in yoga pants with a ponytail and feather earrings.`,
			`A pinata full of scorpions.`,
			`A sad fat dragon with no friends.`,
			`A slightly shittier parallel universe.`,
			`A sofa that says "I have style, but I like to be comfortable."`,
			`A soulful rendition of "Ol' Man River."`,
			`A squadron of moles wearing aviator goggles.`,
			`A sweaty, panting leather daddy.`,
			`A sweet spaceship.`,
			`All of this blood.`,
			`An army of skeletons.`,
			`An ether-soaked rag.`,
			`An unhinged ferris wheel rolling toward the sea.`,
			`Another shot of morphine.`,
			`Basic human decency.`,
			`Beefin' over turf.`,
			`Being awesome at sex.`,
			`Boris the Soviet Love Hammer.`,
			`Bullshit.`,
			`Catastrophic urethral trauma.`,
			`Crabapples all over the fucking sidewalk.`,
			`Crushing Mr. Peanut's brittle body.`,
			`Daddy's belt.`,
			`Death by Steven Seagal.`,
			`Dennis the Menace.`,
			`Dining with cardboard cutouts of the cast of "Friends."`,
			`Double penetration.`,
			`Existing.`,
			`Fetal alcohol syndrome.`,
			`Finding Waldo.`,
			`Fuck Mountain.`,
			`Getting hilariously gang-banged by the Blue Man Group.`,
			`Grandpa's ashes.`,
			`Graphic violence, adult language, and some sexual content.`,
			`Hillary Clinton.`,
			`Hillary Clinton's death stare.`,
			`Intimacy problems.`,
			`Jeff Goldblum.`,
			`Living in a trashcan.`,
			`Loki, the trickster god.`,
			`Making a friend.`,
			`Maximal insertion.`,
			`Me.`,
			`Mild autism.`,
			`Mooing.`,
			`My first kill.`,
			`Nunchuck moves.`,
			`Oncoming traffic.`,
			`One Ring to rule them all.`,
			`Power.`,
			`Pretty Pretty Princess Dress-Up Board Game®.`,
			`Pumping out a baby every nine months.`,
			`Rising from the grave.`,
			`Scrotal frostbite.`,
			`Some really fucked-up shit.`,
			`Special musical guest, Cher.`,
			`Spring break!`,
			`Subduing a grizzly bear and making her your wife.`,
			`Survivor's guilt.`,
			`Swiftly achieving orgasm.`,
			`Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.`,
			`The black Power Ranger.`,
			`The corporations.`,
			`The day the birds attacked.`,
			`The Google.`,
			`The grey nutrient broth that sustains Mitt Romney.`,
			`The hose.`,
			`The human body.`,
			`The mere concept of Applebee's®.`,
			`The mixing of the races.`,
			`The new Radiohead album.`,
			`Tiny nipples.`,
			`Tongue.`,
			`Upgrading homeless people to mobile hotspots.`,
			`Weapons-grade plutonium.`,
			`Wearing an octopus for a hat.`,
			`Whining like a little bitch.`,
			`Whipping a disobedient slave.`,
		},
	}

	AddPack(pack)
}
