package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "cah-fourth-expansion",
		Description: "CAH: Fourth Expansion",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s melts in your mouth, not in your hand.`},
			&PromptCard{Prompt: `%s will win you the Mom of the Year award every time.`},
			&PromptCard{Prompt: `2 fish, 4 potato fritters, 1 scoop of chips and %s, crumbled if possible.`},
			&PromptCard{Prompt: `Affordable healthcare's not the answer.  Only %s can end America's opioid epidemic.`},
			&PromptCard{Prompt: `Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation %s.`},
		},
		Responses: []ResponseCard{
			`10 minute sof decent sex.`,
			`A bunch of naked bridesmaids.`,
			`A dance so face-meltingly hot, you have to go to the restroom and check your underwear.`,
			`A fascist loofa-faced shit-gibbon.`,
			`A foreskin charm bracelet`,
			`A gender studies teacher.`,
			`A horcrux`,
			`A hot air balloon powered by fart gas.`,
			`A Kiwi with lasers for eyes`,
			`A map of Trump's electoral victory.`,
			`A naughty girl`,
			`A sex doll that just wants to be friends.`,
			`A sex machine`,
			`a ship-load of precious sperm`,
			`A unicorn farting rainbows`,
			`Actualizing my potential.`,
			`African Babies`,
			`All the ways the baby blogs convince you you are murdering your unborn child`,
			`Almost having sex in a dream.`,
			`Amendments and Commandments, whichever`,
			`An interspecies orgy.`,
			`Angelina Jolie`,
			`Assassinating the president.`,
			`Blah blah blah`,
			`Bountiful barracks butt stuff.`,
			`Calf implants on an infant.`,
			`Child support payments.`,
			`Crazy raccoons`,
			`Demanding an end to video game addiction`,
			`Depriving white men of the right to vote for 150 years and just seeing what happens.`,
			`Doodle on a cheese doodle.`,
			`Drinking soda`,
			`Exploding so dead you're reincarnated into an abortion.`,
			`Falling into the zoo enclosure.`,
			`Finally getting rid of taxis.`,
			`Fucking a girl so hard her nose bleeds.`,
			`Grand Theft Auto: Fort Lauderdale.`,
			`How awesome it is to be white.`,
			`inner city children`,
			`Intimacy problems.`,
			`Jizzing in your Mother in-law's soup.`,
			`Kibbles 'n Bits12.`,
			`Lots of therapy.`,
			`Modrobes`,
			`my dad's jar of petroleum jelly`,
			`My sex life.`,
			`my Yale College and my Harvard`,
			`Neil Patrick Harris.`,
			`no cock of mine`,
			`Party poopers.`,
			`Prince Charles`,
			`Sharks.`,
			`Smoking crack.`,
			`Snorting coke off the back of a toilet`,
			`Some sort of unstoppable poo gun.`,
			`Spotting your commander at BronyCon.`,
			`Stuffing my balls into a Sega Genesis and pressing the power button.`,
			`Sugar madness.`,
			`The best words. (And a below-average spell-checker.)`,
			`The complex sounds of goats`,
			`The European Union`,
			`The pelican that will one day eat Scarlett Johansson's baby.`,
			`The safest way to have dolphin-sex.`,
			`The secret handshake.`,
			`The skin flute, in A minor.`,
			`The tiny man who lives inside the ATM and hands out all the money.`,
			`Three days without eating in the Arizona desert to reach the American Dream.`,
			`Unraveling 550 reels to look busy for a significant amount of time.`,
			`What looked like a chemical weapons facility but turned out to be a children's hospital.`,
			`Whatever brave hero killed Hitler.`,
			`Whispering to your chaplain that Jesus Christ was a pussy.`,
		},
	}

	AddPack(pack)
}
