package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Fifth Expansion",
		Description: "CAH: Fifth Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `And what did you bring for show and tell?`},
			&PromptCard{Prompt: `Art isn't just a painting in a stuffy museum. Art is alive. Art is _.`},
			&PromptCard{Prompt: `Do the Mahi, get _.`},
			&PromptCard{Prompt: `Do you lack energy? Does it sometimes feel like the whole world is _? Zoloft.`},
			&PromptCard{Prompt: `Don't get me wrong I think what Hitler did and stood for is horrible but you have to admit he was was spot on about _.`},
			&PromptCard{Prompt: `Get rich or die _.`},
			&PromptCard{Prompt: `Having tired of poetry and music, the immortal elves now fill their days with _.`},
			&PromptCard{Prompt: `Hell hath no fury like _.`},
			&PromptCard{Prompt: `HELP WANTED: Need assistance with _. No experience necessary.`},
			&PromptCard{Prompt: `Here is the church
Here is the steeple
Open the doors
And there is _.`},
			&PromptCard{Prompt: `Hi, this is Jim from accounting. We noticed a $1,200 charge labeled "_." Can you explain?`},
			&PromptCard{Prompt: `Hidden behing the Mona Lisa, scientists recently found Da Vinci's original subject: _.`},
			&PromptCard{Prompt: `I don't need to hold onto my youth, I just love _.`},
			&PromptCard{Prompt: `In his final interview, Robin Williams discussed his private battle with _.`},
			&PromptCard{Prompt: `In his new book, author David Sedaris details his life-long love affair with _.`},
			&PromptCard{Prompt: `Lifetime® presents _ - the story of _.`},
			&PromptCard{Prompt: `Now in bookstores: Nancy Drew and the Mystery of _.`},
			&PromptCard{Prompt: `Patient presents with _ . Likely a result of _.`},
			&PromptCard{Prompt: `Well if you'll excuse me, gentlemen, I have a date with _.`},
			&PromptCard{Prompt: `Well, look at what we have here! A big fancy man walkin' like he's _.`},
			&PromptCard{Prompt: `What killed Old Jim?`},
			&PromptCard{Prompt: `What's Mom's best friend?`},
			&PromptCard{Prompt: `Whos afraid of the big bad _.`},
			&PromptCard{Prompt: `Why am I in jail?`},
			&PromptCard{Prompt: `Yorkville's latest fad diet is called _`},
		},

		Responses: []ResponseCard{
			`400 years of colonial atrocities.`,
			`A Chinese cyber attack on Pornhub that cripples morale across the force.`,
			`a creampie`,
			`A disappointing season of Tabletop that's just about tables.`,
			`a face full of period blood`,
			`A giant squid in a wedding gown.`,
			`A mouthful of soup`,
			`A one-way ticket to Mars.`,
			`A powered exoskeleton.`,
			`A recall of hotdogs`,
			`A teaspoon full of toenail clippings`,
			`a whole school of tongues in this belly of mine`,
			`A zesty breakfast burrito.`,
			`AIDS.`,
			`All things divine`,
			`An inability to take a joke.`,
			`An unfulfilling handjob.`,
			`An unmanned center podium.`,
			`Anal Fisting`,
			`ancient porn`,
			`Backwards recordings`,
			`Being obessed with board games.`,
			`Being passively-aggressive on social media.`,
			`Being worth many sparrows.`,
			`Blacking out and causing some serious fucking damage.`,
			`Blown Out O-Ring`,
			`Boring weekends in Amish Country.`,
			`Butt surgery.`,
			`Changing both your last names to "Danger."`,
			`Child-borne IEDs.`,
			`Cutting off your genitalia and mailing it to your celebrity crush.`,
			`Daddy's Grindr account`,
			`Defeating a gorilla in single combat.`,
			`Denzel.`,
			`Doing the right thing.`,
			`ejaculating on your partner's face, letting it dry, and then peeling it off in one piece`,
			`enormous drums`,
			`Figuring out how to keep a woman with really small, flexible hands restrained in bondage cuffs.`,
			`Free introductory seminars at Trump University Community College.`,
			`Genital piercings.`,
			`Getting caught masturbating to hentai porn.`,
			`Getting drugs off the street and into my body.`,
			`Getting eaten alive by puppies.`,
			`Giant Strap-ons`,
			`Going to a strip club to vent your problems to a complete stranger.`,
			`Having big dreams but no realistic way to achieve them.`,
			`Mom's new haircut.`,
			`My bright pink fuckhole.`,
			`My dick in your mouth.`,
			`My fist`,
			`Not caring. At all.`,
			`Oiled up bodybuilders wearing only a thong.`,
			`Outdated gender norms.`,
			`P.F. Chang's fusion of casual and formal cuisine.`,
			`RussianBrides.com`,
			`Seeing Suzy Cato in a completely new light`,
			`Seeing what happens when you lock people in a room with hungry seagulls.`,
			`September 11th.`,
			`Slowly evaporating.`,
			`Social media evangelization.`,
			`Some sort of Asian.`,
			`Sub drop.*`,
			`The ability known as "retardation."`,
			`The bastard seagull who stole my chips.`,
			`The black lung.`,
			`The eighth graders.`,
			`The Girl Next Door`,
			`The inability to grow facial hair`,
			`The Passion of Christ.`,
			`The Sword of Damocles`,
			`The time I figured out that "Twinkle, Twinkle" and the "Alphabet Song" had the same tune`,
			`the undeniable dark side of mankind`,
			`The White House Coal Garden.`,
			`Too much edibles.`,
			`unrequited love`,
			`Vegetarians or humanitarians, whichever`,
			`Wearing glasses to look as if you are smart.`,
			`Westies`,
		},
	}

	AddPack(pack)
}
