package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Office Pack",
		Description: "Office and workplace themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The worst thing about working in an office is %s.`},
			&PromptCard{Prompt: `My boss is known for %s.`},
			&PromptCard{Prompt: `I would quit my job if %s happened.`},
			&PromptCard{Prompt: `The office party was ruined by %s.`},
			&PromptCard{Prompt: `The break room is the only place where %s.`},
			&PromptCard{Prompt: `What's the most unprofessional thing you can do at work?`},
		},
		Responses: []ResponseCard{
			`Fluorescent lights`,
			`Cubicles`,
			`A water cooler`,
			`A break room`,
			`Burnt coffee`,
			`Expired lunch from the fridge`,
			`Karen from accounting`,
			`Derek from sales`,
			`Mandatory meetings`,
			`PowerPoint presentations`,
			`Conference calls`,
			`Email threads`,
			`Reply all on group emails`,
			`A passive-aggressive email`,
			`A forwarded chain email`,
			`Office gossip`,
			`Water cooler talk`,
			`A casual Friday`,
			`Business casual dress code`,
			`Dress for the job you want`,
			`A promotion`,
			`A pay raise`,
			`A layoff`,
			`A resignation letter`,
			`An HR violation`,
			`A hostile work environment`,
			`Office politics`,
			`Backstabbing coworkers`,
			`A toxic boss`,
			`A micromanager`,
			`Working late`,
			`Working weekends`,
			`No work-life balance`,
			`Burnout`,
			`A mental breakdown`,
			`Throwing your computer`,
			`Flipping the desk`,
			`Walking out mid-meeting`,
			`Punching a coworker`,
			`A office romance`,
		},
	}
	AddPack(pack)
}
