package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Sixth Expansion",
		Description: "CAH: Sixth Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `"This workplace has been 0 days without _."`},
			&PromptCard{Prompt: `Angelina Jolie will now be special envoy for _.`},
			&PromptCard{Prompt: `Behind every successful man is _.`},
			&PromptCard{Prompt: `Come to Toronto for the _, stay for the _`},
			&PromptCard{Prompt: `Don't worry, _ is not as hard as it seems.`},
			&PromptCard{Prompt: `Everyday has 86,400 seconds. And I'm always a second away from _.`},
			&PromptCard{Prompt: `I have an agreement with my significant other, if we meet _, I am allowed to have sex with them with no consequences.`},
			&PromptCard{Prompt: `I went to the desert and ate of the peyote cactus. Turns out my spirit animal is _.`},
			&PromptCard{Prompt: `I would be on board with Scientology if it weren't for _.`},
			&PromptCard{Prompt: `I'm never going to be rich and famous because I'm too busy _.`},
			&PromptCard{Prompt: `I'm sorry, Professor, but I couldn't complete my homework because of _.`},
			&PromptCard{Prompt: `If you had to pay me for sex, what would you do first? _.`},
			&PromptCard{Prompt: `Jellicle Cats come out tonight, Jellicle Cats come one, come all, the time for _ is now, Jellicles come to the Jellicle Ball.`},
			&PromptCard{Prompt: `Listen son, your mother and I are getting a divorce, and it's because of _.`},
			&PromptCard{Prompt: `My grandkids need _.`},
			&PromptCard{Prompt: `Puff the Magic _.`},
			&PromptCard{Prompt: `The six things I could never do without: oxygen, facebook, chocolate, netflix, friends, and _ LOL!`},
			&PromptCard{Prompt: `This is an absolutely hilarious video. Please share it! #_`},
			&PromptCard{Prompt: `To boost morale after Hurricane Harvey, President Trump gave a guy in a pick-up truck _.`},
			&PromptCard{Prompt: `Tonight's Final Jeopardy category is _.`},
			&PromptCard{Prompt: `When I was a little girl I always wanted to _.`},
			&PromptCard{Prompt: `Why would I want _ stuffed down my throat?`},
			&PromptCard{Prompt: `YAAAAAAS! You are serving me _ realness!`},
			&PromptCard{Prompt: `You are under arrest for _, again!`},
			&PromptCard{Prompt: `You like my cupcakes? I made them myself. The secret ingredient is _.`},
			&PromptCard{Prompt: `You won't find this in textbooks, but _ is the real reason the US entered World War II.`},
		},

		Responses: []ResponseCard{
			`A bathroom only for poop.`,
			`A bowl of gourds.`,
			`A button that when you press it, there's jazz.`,
			`A constant, deafening queef.`,
			`a man who isn't afraid to talk about his feelings`,
			`A phantasmagoria of anal delights.`,
			`A plan to kill everyone you meet.`,
			`A post-deployment RED HORSE troop fucking everyone and everything in their path.`,
			`A selfie`,
			`A turkey baster`,
			`A whole new kind of "play date"`,
			`An orcgasm.`,
			`An overworked Chippendales® dancer.`,
			`Bathing naked in a moonlit grove.`,
			`Being a total Miranda.`,
			`Being judged not by the color of your skin, but by the content of your character.`,
			`Being pregnant with dolphin babies.`,
			`Below the Waist`,
			`Breastfeeding a ten-year-old.`,
			`Bullfrogs`,
			`Cancerous USAF leadership.`,
			`Cooties`,
			`Crippling status anxiety.`,
			`Crying babies.`,
			`Cute cat videos`,
			`Eating Tom Selleck's mustache to gain his powers.`,
			`Ejaculating into ham slices and sticking them all over a woman`,
			`every robust healthy boy`,
			`Filling every orifice with butterscotch pudding.`,
			`Forgetting grandma's first name.`,
			`Generation Xers`,
			`Getting all the good dick.`,
			`Getting skin cancer after 5 minutes at Takapuna beach`,
			`Growing up in Catholic school and not being better for it.`,
			`Gymnastic leotards that slide up your butt.`,
			`Impeaching "The View."`,
			`Important votes from Down Syndrome community.`,
			`Kamikaze pilots.`,
			`likes to my facebook post`,
			`measureless sobbing`,
			`MORTAL KOMBAT.`,
			`Never nude orgies.`,
			`No more beersies`,
			`One weird lookin' toe.`,
			`our o'erhasty marriage`,
			`Owning and operating a Chili's franchise.`,
			`Peeing into everyone's mouth.`,
			`Put breastmilk on it.`,
			`Raccoon: The other, other dark meat`,
			`Reading the entire Harry Potter series in one week`,
			`Ripping fat vapes.`,
			`Robots with human faces`,
			`Setting someone on fire at Burning Man.`,
			`Shapeshifters.`,
			`Shitting an adult diaper.`,
			`Such a nasty group of people.`,
			`Sucking all the oil out of the planet and fucking off to Mars.`,
			`Sudden Poop Explosion Disease.`,
			`Teaching a politician how to tell the truth.`,
			`Texting "lol" to express self-consciousness.`,
			`The all-seeing eye`,
			`The amount of medals I have.`,
			`The color guard team captain`,
			`The Denver Satanic Gardens.`,
			`the Elder Wand`,
			`The Hawaiian goddess Kapo and her flying detachable vagina.`,
			`The Man`,
			`The Pre-Nup of Allegiance.`,
			`The sweet sound of snot right before a cup of hot chocolate.`,
			`Throwing the baby out with the bathwater.`,
			`Totaling a manual-transmission car two seconds after trying to drive it.`,
			`Treating a Chihuahua like a small child and putting it in a stroller.`,
			`turning tricks`,
			`Two words: on sale`,
			`Unsolicited anal pleasure.`,
			`Walking into a room and forgetting what you were looking for.`,
			`Whatever, who even gives a shit.`,
		},
	}

	AddPack(pack)
}
