package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: UK Conversion Kit",
		Description: "CAH: UK Conversion Kit pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s? Jim'll fix it!`},
			&PromptCard{Prompt: `%s. That's why mums go to Iceland.`},
			&PromptCard{Prompt: `%s. Once you pop, the fun don't stop!`},
			&PromptCard{Prompt: `And the Lord said, "Let there be %s". And it was GOOD.`},
			&PromptCard{Prompt: `Channel 5's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `Channel 9 is pleased to present its new variety show, "Hey Hey It's %s."`},
			&PromptCard{Prompt: `Coming to the West End this year, %s: The Musical.`},
			&PromptCard{Prompt: `Dear Allah, if I promise to stop %s will you let me into heaven and give me 72 virgins?`},
			&PromptCard{Prompt: `In high school, I was popular with the football team for %s.`},
			&PromptCard{Prompt: `In Wormwood Scrubs, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `Next on Sky Sports: The World Championship of %s.`},
			&PromptCard{Prompt: `Nobody expects the Spanish Inquisition! Our chief weapons are fear, surprise, and %s.`},
			&PromptCard{Prompt: `TFL apologizes for the delay in train service due to %s.`},
			&PromptCard{Prompt: `The Natural History Museum has just opened an interactive exhibit on %s.`},
			&PromptCard{Prompt: `The theme for our senior prom will be %s.`},
			&PromptCard{Prompt: `Today we honor St. Mungo, the patron saint of %s.`},
			&PromptCard{Prompt: `What are the 3 secrets for a long and happy marriage?`},
			&PromptCard{Prompt: `What did I bring back from Bali?`},
			&PromptCard{Prompt: `What killed Mister Rogers?`},
			&PromptCard{Prompt: `When I am Prime Minister of the United Kingdom, I will create the Ministry of %s.`},
		},

		Responses: []ResponseCard{
			`41 million Americans living in poverty.`,
			`a bitch slap`,
			`A Chelsea smile.`,
			`A far, far away place.`,
			`A gingerbread man living in a home made of his own flesh.`,
			`A mad, bad duck in a petting zoo.`,
			`A madman who lives in a policebox and kidnaps women.`,
			`A nice little drone strike`,
			`A positive male role model.`,
			`A sober Irishman.`,
			`A thousand shitty wedding planning websites.`,
			`A Violet Wand with multiple attachments.*`,
			`A white, straight, cis male.`,
			`an arm thrust forth from the grass over a grave`,
			`An EO violation.`,
			`Anything with a hole.`,
			`Badly-botched botox`,
			`Being ignored.`,
			`Bloodthirsty dictators.`,
			`Blowing up the Moon.`,
			`Buckfast Tonic Wine`,
			`Cheerful blowjob robots.`,
			`Chlamydia`,
			`Cotton candy flavored lube`,
			`Daddies Brown Sauce.`,
			`David Cameron's bacon-flavoured balls.`,
			`Dogging`,
			`Doing a somersault and barfing.`,
			`Drum circles.`,
			`Ed Sheeran's receding hairline`,
			`English cuisine.`,
			`Exceedingly low standards.`,
			`failing a personality test`,
			`Five miso soups, four seaweed salads, three soy burger dinners, two tofu dog platters, and one pasta with meatless meatballs.`,
			`Gary Sinise's unrelenting hard-on for all things military.`,
			`Gentleman's Relish.®`,
			`Germany invading Russia in the summer.`,
			`Getting naked and watching Nickelodeon.`,
			`Getting wet`,
			`Hagrid and Madame Maxime roleplay.`,
			`Hurricane Katrina refugees.`,
			`Jafar.`,
			`Jeff Bezos.`,
			`Jell-O shots`,
			`Jimmy Savile`,
			`Just turned 18.`,
			`Leaking milk during sex`,
			`Madeleine McCann's new age progression image`,
			`Max Key's obsession with topless photoshoots`,
			`Mimosas at the playdate`,
			`Minions`,
			`One for the homies.`,
			`Pronouncing the p in raspberry.`,
			`Queen Elsa`,
			`Ripping open a man's chest and pulling out his still-beating heart.`,
			`Rubbing chocolate pudding all over Bill Cosby's nipples.`,
			`Scalping.`,
			`Scouting for disciples.`,
			`Shitting out a screaming face.`,
			`Slapping a racist old lady.`,
			`Spanking`,
			`The black half of Barack Obama.`,
			`The Blue Bulls rugby team.`,
			`The entire cast of Downtown Abbey.`,
			`The Friend Zone`,
			`The Hitachi Magic Wand.*`,
			`The honourable member, shut up.`,
			`The Northern Lights`,
			`The Phantom of the Opera.`,
			`the stinking elder`,
			`The sudden interest in the opposite sex`,
			`The way Rachel Hunter devours her Trumpets`,
			`Torn pop-up books.`,
			`Trevor Noah`,
		},
	}

	AddPack(pack)
}
