package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Third Expansion",
		Description: "CAH: Third Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `_: I volunteer as tribute!`},
			&PromptCard{Prompt: `_. Betcha can't have just one!`},
			&PromptCard{Prompt: `A superior officer approaches. You salute and say _, and they respond with _.`},
			&PromptCard{Prompt: `after my grandma passed gas, she learned over to my grandpa and said _`},
			&PromptCard{Prompt: `And what do we say to the God of Death?`},
			&PromptCard{Prompt: `As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _.`},
			&PromptCard{Prompt: `As part of its hazing process, the frat forced its recruits to try _.`},
			&PromptCard{Prompt: `Calm down, dear, it's only _.`},
			&PromptCard{Prompt: `During his childhood, Salvador Dali produced hundreds of paintings of _.`},
			&PromptCard{Prompt: `Find a _ and pick it up, and all the day you'll have good luck.`},
			&PromptCard{Prompt: `Having sex with Hillary is like having sex with _.`},
			&PromptCard{Prompt: `Hey Chardonnay, wanna see _.`},
			&PromptCard{Prompt: `I'm sorry, sir, but your insurance plan doesn't cover injuries caused by _.`},
			&PromptCard{Prompt: `In the UK it's now socially acceptable to have _ in public`},
			&PromptCard{Prompt: `Little Boy Blue go blow your _.`},
			&PromptCard{Prompt: `Loyalty, Duty, Respect, Selfless, Service, Honor, Integrity, Personal Courage, and _: the newest Army Value.`},
			&PromptCard{Prompt: `Money from state lotteries goes to _ to buy _.`},
			&PromptCard{Prompt: `My heart skipped a beat when he took my hand, leaned in close, and whispered "_."`},
			&PromptCard{Prompt: `My love for you is like _: peaceful and deep.`},
			&PromptCard{Prompt: `The Blues have as much chance of winning as _ has at getting laid.`},
			&PromptCard{Prompt: `To protect the integrity of our democracy, voting booths in 2020 will be monitored by _.`},
			&PromptCard{Prompt: `Twas the night before Christmas, and all through the house,

not a creature was stirring, not even _.`},
			&PromptCard{Prompt: `What made me this way?`},
			&PromptCard{Prompt: `When you go to the polls on Tuesday, remember:  a vote for me is a vote for _.`},
			&PromptCard{Prompt: `With every year that passes, I find it harder and harder to be _.`},
		},

		Responses: []ResponseCard{
			`A black male in his early 20s, last seen wearing a hoodie.`,
			`A boo-boo.`,
			`A botched circumcision.`,
			`A cat video so cute that your eyes roll back and your spine slides out of your anus.`,
			`A cop who is also a dog.`,
			`A greased-up Matthew McConaughey.`,
			`A Japanese toaster you can fuck.`,
			`A lamprey swimming up the toilet and latching onto your taint.`,
			`A pile of squirming bodies.`,
			`A PowerPoint presentation.`,
			`A spontaneous conga line.`,
			`A surprising amount of hair.`,
			`A vagina that leads to another dimension.`,
			`Actually getting shot, for real.`,
			`All my friends dying.`,
			`An all-midget production of Shakespeare's Richard III.`,
			`An ass disaster.`,
			`An unstoppable wave of fire ants.`,
			`Bill Clinton, naked on a bearskin rug with a saxophone.`,
			`Blood farts.`,
			`Blowing some dudes in an alley.`,
			`Buying the right pants to be cool.`,
			`Chugging a lava lamp.`,
			`Cock.`,
			`Crying into the pages of Sylvia Plath.`,
			`Demonic possession.`,
			`Disco fever.`,
			`Drinking ten 5-hour ENERGYs® to get fifty continuous hours of energy.`,
			`Dying alone and in pain.`,
			`Eating Tom Selleck's mustache to gain his powers.`,
			`Filling every orifice with butterscotch pudding.`,
			`Fisting.`,
			`Flying robots that kill people.`,
			`Gay aliens.`,
			`Getting your dick stuck in a Chinese finger trap with another dick.`,
			`Girls that always be textin'.`,
			`Going around punching people.`,
			`Having sex on top of a pizza.`,
			`Having shotguns for legs.`,
			`Indescribable loneliness.`,
			`Jumping out at people.`,
			`Letting everyone down.`,
			`Mufasa's death scene.`,
			`My manservant, Claude.`,
			`Not contributing to society in any meaningful way.`,
			`Not having sex.`,
			`Nothing.`,
			`Putting an entire peanut butter and jelly sandwich into the VCR.`,
			`Racial profiling.`,
			`Reverse cowgirl.`,
			`Roland the Farter, flatulist to the king.`,
			`Running naked through a mall, pissing and shitting everywhere.`,
			`Samuel L. Jackson.`,
			`Screaming like a maniac.`,
			`Self-flagellation.`,
			`Shutting the fuck up.`,
			`Slapping a racist old lady.`,
			`Sneezing, farting, and cumming at the same time.`,
			`Some douche with an acoustic guitar.`,
			`Some kind of bird-man.`,
			`Spending lots of money.`,
			`That ass.`,
			`The entire Internet.`,
			`The Harlem Globetrotters.`,
			`The Land of Chocolate.`,
			`The moist, demanding chasm of his mouth.`,
			`The primal, ball-slapping sex your parents are having right now.`,
			`The Quesadilla Explosion Salad™ from Chili's.®`,
			`The systematic destruction of an entire people and their way of life.`,
			`The thin veneer of situational causality that underlies porn.`,
			`The way white people is.`,
			`Three months in the hole.`,
			`Unlimited soup, salad, and breadsticks.`,
			`Velcro™.`,
			`Vietnam flashbacks.`,
			`Vomiting mid-blowjob.`,
			`Warm, velvety muppet sex.`,
		},
	}

	AddPack(pack)
}
