package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Fourth Expansion",
		Description: "CAH: Fourth Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `_ melts in your mouth, not in your hand.`},
			&PromptCard{Prompt: `_ will win you the Mom of the Year award every time.`},
			&PromptCard{Prompt: `2 fish, 4 potato fritters, 1 scoop of chips and _, crumbled if possible.`},
			&PromptCard{Prompt: `Affordable healthcare's not the answer.  Only _ can end America's opioid epidemic.`},
			&PromptCard{Prompt: `Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation _.`},
			&PromptCard{Prompt: `As long as my kid doesn't grow up to be _, I'm happy.`},
			&PromptCard{Prompt: `Dammit, Gary.  You can't just solve every problem with _.`},
			&PromptCard{Prompt: `Dear Mom and Dad, Camp is fun. I like capture the flag. Yesterday, one of the older kids taught me about _. I love you, Casey`},
			&PromptCard{Prompt: `Do not go gentle into that good night. Rage, rage against _?`},
			&PromptCard{Prompt: `Every Sunday "Insert Name" goes to market to sell _, and every time comes home with Magic Beans.`},
			&PromptCard{Prompt: `Forget Fifty Shades of Grey...

Give me Fifty Shades of _!`},
			&PromptCard{Prompt: `Honey, I have good news, and bad news.  The good news is that I'm _.  The bad news is that I'm _.`},
			&PromptCard{Prompt: `How am I going to kill myself?`},
			&PromptCard{Prompt: `I am become _, the destroyer of worlds.`},
			&PromptCard{Prompt: `I'm pretty sure I'm high right now, because I'm absolutely mesmerized by _.`},
			&PromptCard{Prompt: `I'm sorry, this table is reserved for _.`},
			&PromptCard{Prompt: `If you can't love yourself, how the hell you gonna love _?`},
			&PromptCard{Prompt: `In Rome, there are whisperings that the Vatican has a secret room devoted to _.`},
			&PromptCard{Prompt: `In the category _, the first prize is awarded to _.`},
			&PromptCard{Prompt: `It makes me sad to think about?`},
			&PromptCard{Prompt: `Many questioned the Smithsonian's decision to feature an exhibit devoted to _.`},
			&PromptCard{Prompt: `Other parents worry about _ but I stress over _.`},
			&PromptCard{Prompt: `She's a lady in the streets, _ in the sheets.`},
			&PromptCard{Prompt: `The Juice is loose.  And by Juice I mean _.`},
			&PromptCard{Prompt: `This is the way the world ends
This is the way the world ends
Not with a bang but with _.`},
			&PromptCard{Prompt: `This year's trendiest card game:

"_ Against _."`},
			&PromptCard{Prompt: `We played baseball with _.`},
			&PromptCard{Prompt: `Wes Anderson's new movie is a whimsical look at _ starring _.`},
			&PromptCard{Prompt: `What's going on with your female servicemembers?`},
			&PromptCard{Prompt: `You guys, you can buy _ on the dark web.`},
			&PromptCard{Prompt: `Young lady, you better knock it off with _ or you're grounded!`},
		},

		Responses: []ResponseCard{
			`10 minute sof decent sex.`,
			`A bunch of naked bridesmaids.`,
			`A dance so face-meltingly hot, you have to go to the restroom and check your underwear.`,
			`A fascist loofa-faced shit-gibbon.`,
			`A foreskin charm bracelet`,
			`A gender studies teacher.`,
			`A horcrux`,
			`A hot air balloon powered by fart gas.`,
			`A Kiwi with lasers for eyes`,
			`A map of Trump's electoral victory.`,
			`A naughty girl`,
			`A sex doll that just wants to be friends.`,
			`A sex machine`,
			`a ship-load of precious sperm`,
			`A unicorn farting rainbows`,
			`Actualizing my potential.`,
			`African Babies`,
			`All the ways the baby blogs convince you you are murdering your unborn child`,
			`Almost having sex in a dream.`,
			`Amendments and Commandments, whichever`,
			`An interspecies orgy.`,
			`Angelina Jolie`,
			`Assassinating the president.`,
			`Blah blah blah`,
			`Bountiful barracks butt stuff.`,
			`Calf implants on an infant.`,
			`Child support payments.`,
			`Crazy raccoons`,
			`Demanding an end to video game addiction`,
			`Depriving white men of the right to vote for 150 years and just seeing what happens.`,
			`Doodle on a cheese doodle.`,
			`Drinking soda`,
			`Exploding so dead you're reincarnated into an abortion.`,
			`Falling into the zoo enclosure.`,
			`Finally getting rid of taxis.`,
			`Fucking a girl so hard her nose bleeds.`,
			`Grand Theft Auto: Fort Lauderdale.`,
			`How awesome it is to be white.`,
			`inner city children`,
			`Intimacy problems.`,
			`Jizzing in your Mother in-law's soup.`,
			`Kibbles 'n Bits™.`,
			`Lots of therapy.`,
			`Modrobes`,
			`my dad's jar of petroleum jelly`,
			`My sex life.`,
			`my Yale College and my Harvard`,
			`Neil Patrick Harris.`,
			`no cock of mine`,
			`Party poopers.`,
			`Prince Charles`,
			`Sharks.`,
			`Smoking crack.`,
			`Snorting coke off the back of a toilet`,
			`Some sort of unstoppable poo gun.`,
			`Spotting your commander at BronyCon.`,
			`Stuffing my balls into a Sega Genesis and pressing the power button.`,
			`Sugar madness.`,
			`The best words. (And a below-average spell-checker.)`,
			`The complex sounds of goats`,
			`The European Union`,
			`The pelican that will one day eat Scarlett Johansson's baby.`,
			`The safest way to have dolphin-sex.`,
			`The secret handshake.`,
			`The skin flute, in A minor.`,
			`The tiny man who lives inside the ATM and hands out all the money.`,
			`Three days without eating in the Arizona desert to reach the American Dream.`,
			`Unraveling 550 reels to look busy for a significant amount of time.`,
			`What looked like a chemical weapons facility but turned out to be a children's hospital.`,
			`Whatever brave hero killed Hitler.`,
			`Whispering to your chaplain that Jesus Christ was a pussy.`,
		},
	}

	AddPack(pack)
}
