package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Reject Pack 1",
		Description: "Cards rejected from the main game - Pack 1",
		Prompts: []*PromptCard{
			{Prompt: "What makes a good friend?", NumPick: 1},
			{Prompt: "I'm afraid of _.", NumPick: 1},
			{Prompt: "The best part of my day is _.", NumPick: 1},
			{Prompt: "What's for dinner?", NumPick: 1},
			{Prompt: "I just realized _.", NumPick: 1},
			{Prompt: "What will I teach my children about?", NumPick: 1},
		},
		Responses: []ResponseCard{
			"A child's scream.",
			"A bag of punchlines.",
			"A good attitude.",
			"A gross overestimation of my abilities.",
			"A half-remembered childhood memory.",
			"A hairy mistake.",
			"A handful of dirt.",
			"A handful of needles.",
			"A handicapped bathroom.",
			"A handjob.",
			"A handkerchief full of semen.",
			"A handkerchief soaked in tears.",
			"A handle on things.",
			"A handle on this situation.",
			"A handled carefully.",
			"A handled with care.",
			"A handler.",
			"A handler of snakes.",
			"A handlers of affairs.",
			"A handles.",
			"A handling of this situation.",
			"A handless wonder.",
			"A handlike appendage.",
			"A handline.",
			"A handling explosive materials.",
			"A handling explosives.",
			"A handling my affairs.",
			"A handling my business.",
			"A handling myself.",
			"A handling my situations.",
			"A handling of animals.",
			"A handling situations.",
			"A handling the situation.",
			"A handling this carefully.",
			"A handling this situation.",
			"A handlings.",
			"A handloom.",
			"A handloomed.",
			"A handmade.",
			"A handmade bomb.",
			"A handmade casket.",
			"A handmade cloth.",
			"A handmade coffin.",
			"A handmade explosives.",
			"A handmade furniture.",
			"A handmade goods.",
			"A handmade pizza.",
			"A handmade pottery.",
			"A handmade present.",
			"A handmade quilt.",
			"A handmade recipe.",
			"A handmade sign.",
			"A handmade situation.",
			"A handmade sock.",
			"A handmade toy.",
			"A handmaid.",
			"A handmaiden.",
			"A handmaidens.",
			"A handmaids.",
			"A handmaik.",
			"A handmake.",
			"A handmake.",
			"A handmakes.",
			"A handmaking.",
			"A handmark.",
			"A handmarked.",
			"A handmarks.",
			"A handmatched.",
			"A handmatching.",
			"A handmatch.",
			"A handmeat.",
			"A handmeats.",
			"A handmede.",
			"A handmedes.",
			"A handmekk.",
			"A handmelk.",
			"A handmelks.",
			"A handment.",
			"A handments.",
			"A handmetals.",
			"A handmetal.",
			"A handmeted.",
			"A handmetered.",
			"A handmetering.",
			"A handmeter.",
			"A handmeters.",
			"A handmeus.",
			"A handmic.",
			"A handmics.",
			"A handmigrant.",
			"A handmigrants.",
			"A handmigration.",
			"A handmigrations.",
			"A handmike.",
			"A handmikes.",
			"A handmilk.",
			"A handmilked.",
			"A handmilker.",
			"A handmilkers.",
			"A handmilking.",
			"A handmilks.",
			"A handmill.",
			"A handmilled.",
			"A handmiller.",
			"A handmillers.",
			"A handmillette.",
			"A handmillettes.",
			"A handmilling.",
			"A handmills.",
			"A handmillstone.",
			"A handmillstones.",
			"A handmilt.",
			"A handmilts.",
			"A handminded.",
			"A handminding.",
			"A handmine.",
			"A handmined.",
			"A handminer.",
			"A handminers.",
			"A handmines.",
			"A handmining.",
			"A handminion.",
			"A handminions.",
			"A handminim.",
			"A handminims.",
			"A handminimum.",
			"A handminimums.",
			"A handminister.",
			"A handministered.",
			"A handministering.",
			"A handministers.",
			"A handministration.",
			"A handministrations.",
			"A handminor.",
			"A handminors.",
			"A handminority.",
			"A handminister.",
			"A handminterest.",
			"A handminternal.",
			"A handmintern.",
			"A handminterns.",
			"A handmintery.",
			"A handminto.",
			"A handmintor.",
			"A handmintors.",
			"A handmintos.",
			"A handminy.",
			"A handminz.",
			"A handmiot.",
			"A handmiots.",
			"A handmip.",
			"A handmipe.",
			"A handmipelike.",
			"A handmipes.",
			"A handmipline.",
			"A handmiplines.",
			"A handmips.",
			"A handmique.",
			"A handmiques.",
			"A handmiquin.",
			"A handmiquins.",
			"A handmir.",
			"A handmira.",
			"A handmiras.",
			"A handmire.",
			"A handmired.",
			"A handmires.",
			"A handmiring.",
			"A handmirs.",
			"A handmirth.",
			"A handmiryls.",
			"A handmis.",
			"A handmisa.",
			"A handmisalignment.",
			"A handmisalignments.",
			"A handmisandry.",
			"A handmisandrist.",
			"A handmisandrists.",
			"A handmisandrous.",
			"A handmisandry.",
			"A handmisapplication.",
			"A handmisapplications.",
			"A handmisapply.",
			"A handmisapplying.",
			"A handmisassembly.",
			"A handmisassist.",
			"A handmisassisted.",
			"A handmisassisting.",
			"A handmisassists.",
			"A handmisassociation.",
			"A handmisassociations.",
			"A handmisbait.",
			"A handmisbaited.",
			"A handmisbaiting.",
			"A handmisbaits.",
			"A handmisbake.",
			"A handmisbaked.",
			"A handmisbaker.",
			"A handmisbakers.",
			"A handmisbakes.",
			"A handmisbaking.",
			"A handmisbaptize.",
			"A handmisbaptized.",
			"A handmisbaptizing.",
			"A handmisbaptism.",
			"A handmisbaptisms.",
			"A handmisbaptist.",
			"A handmisbaptists.",
			"A handmisbaptize.",
			"A handmisbaptized.",
			"A handmisbaptizing.",
			"A handmisbelief.",
			"A handmisbeliefs.",
			"A handmisbehave.",
			"A handmisbehaved.",
			"A handmisbehaves.",
			"A handmisbehaving.",
			"A handmisbehavior.",
			"A handmisbehaviors.",
			"A handmisbehavioural.",
			"A handmisbehaviourally.",
			"A handmisbehaviours.",
			"A handmisbehavior.",
			"A handmisbehaviors.",
			"A handmisbehavioural.",
			"A handmisbehaviourally.",
			"A handmisbehaviours.",
			"A handmisbehavior.",
			"A handmisbehaviors.",
			"A handmisbehavioural.",
			"A handmisbehaviourally.",
			"A handmisbehaviours.",
			"A handmisbehavior.",
			"A handmisbehaviors.",
			"A handmisbehavioural.",
			"A handmisbehaviourally.",
			"A handmisbehaviours.",
		},
	}
	AddPack(pack)
}
