package cardsagainstdiscord

func init() {
pack := &CardPack{
Name:        "first",
Description: "CAH: First Expansion",
Prompts: []*PromptCard{
			&PromptCard{Prompt: `An international tribunal has found %s guilty of %s.`},
			&PromptCard{Prompt: `And I would have gotten away with it, too, if it hadn't been for %s!`},
			&PromptCard{Prompt: `Awww, sick! I just saw this skater do a 720 kickflip into %s!`},
			&PromptCard{Prompt: `Dear Substitute Teacher, could you please stop %s?`},
			&PromptCard{Prompt: `DOCTOR:
What seems to be the problem?

YOU: 
%s.`},
			&PromptCard{Prompt: `Future Historians will agree that %s marked the beginning of America's decline.`},
			&PromptCard{Prompt: `He who controls %s controls the world.`},
			&PromptCard{Prompt: `I left Hamilton because I heard about %s's obsession with %s.`},
			&PromptCard{Prompt: `In a pinch, %s can be a suitable substitute for %s.`},
			&PromptCard{Prompt: `In his new summer comedy, Rob Schneider is %s trapped in the body of %s.`},
			&PromptCard{Prompt: `In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated %s.`},
			&PromptCard{Prompt: `In some cultures, %s is considered a good omen.`},
			&PromptCard{Prompt: `In the distant future, historians will agree that %s marked the beginning of America's decline.`},
			&PromptCard{Prompt: `Michael Bay's new three-hour action epic pits %s against %s.`},
			&PromptCard{Prompt: `My porn-star name would be %s; and I'm famous for %s.`},
			&PromptCard{Prompt: `Next season on Man vs, Wild, Bear Grylls must survive the depths of the Amazon with only %s and his wits.`},
			&PromptCard{Prompt: `Next week on Discovery Channel, one man must survive in the depths of the Amazon with only %s and his wits.`},
			&PromptCard{Prompt: `Science will never explain the origin of %s.`},
			&PromptCard{Prompt: `Science will never explain the origin of %s.`},
			&PromptCard{Prompt: `The CIA now interrogates enemy agents by repeatedly subjecting them to %s.`},
			&PromptCard{Prompt: `The secret to getting your adopted African street dog back into the United States is %s.`},
			&PromptCard{Prompt: `The socialist governments of Scandinavia have declared that access to %s is a basic human right.`},
			&PromptCard{Prompt: `This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only %s and his wits.`},
			&PromptCard{Prompt: `What came in the mail today?`},
			&PromptCard{Prompt: `What has been seen cannot be unssen! I just witnessed %s.`},
			&PromptCard{Prompt: `What's the gift that keeps on giving?`},
			&PromptCard{Prompt: `When asked about the biggest threat facing the nation, 60% of Americans said %s.`},
			&PromptCard{Prompt: `When i pooped, what came out?`},
		},
		Responses: []ResponseCard{
			`24-hour media coverage.`,
			`A beached whale.`,
			`A big black dildo.`,
			`A bloody pacifier.`,
			`A crappy little hand.`,
			`A fat Batman with a sopping wet scrotum.`,
			`A Japanese tourist who wants something very badly but cannot communicate it.`,
			`a low sucking sound`,
			`A nuanced critique.`,
			`A panty raid.`,
			`A passionate Latino lover.`,
			`A plunger to the face.`,
			`A rival dojo.`,
			`A smiling black man, a latina businesswoman, a cool Asian, and some whites.`,
			`A wedding reception. Again.`,
			`A woman scorned.`,
			`An atomic wedgie.`,
			`An Etsy steampunk strap-on.`,
			`An Ex-Porn Star Kindergarten Teacher`,
			`Andre the Giant's enormous, leathery scrotum.`,
			`Appalachian swamp cannibals`,
			`Appreciative snapping.`,
			`Ashton Kutcher.`,
			`Beating your wives.`,
			`Being a clever little girl.`,
			`Being a dumb ox.`,
			`Big Bird's brown, crusty asshole.`,
			`Blaxploitation.`,
			`Bosveld lapa porn.`,
			`Breaking nip slip news.`,
			`Carnies.`,
			`Clams.`,
			`Clenched butt cheeks.`,
			`Converting your sex dungeon into a baby room`,
			`Coughing into a vagina.`,
			`Cutting.`,
			`Dancing with a broom.`,
			`Deflowering a princess.`,
			`deformities floundering in seas of blood and blue paint`,
			`Dorito breath.`,
			`Eating an entire box of chocolates.`,
			`Enormous Scandinavian women.`,
			`Fabricating statistics.`,
			`Finding a skeleton.`,
			`Gandalf's perfectly shaped eyebrows.`,
			`Genetically modified organisms`,
			`George Clooney's musk.`,
			`Getting abducted by Peter Pan.`,
			`Getting in her pants, politely.`,
			`Glamping with Muammar Gaddafi.`,
			`Good grammar.`,
			`Having a pint with Aquinas.`,
			`Hire that Stripper`,
			`Historical revisionism.`,
			`Insatiable bloodlust.`,
			`Jafar.`,
			`Jean-Claude Van Damme in slow motion.`,
			`Jean-Claude Van Damme.`,
			`Just the tip.`,
			`Liam Neeson`,
			`Literally fucking the shit out of someone.`,
			`Mad hacky-sack skills.`,
			`Making the printer work.`,
			`Media coverage.`,
			`Medieval TimesÂ® Dinner & Tournament.`,
			`Mom's ability to take a cock.`,
			`Moral bankruptcy.`,
			`My magic awand`,
			`Neil Patrick Harris.`,
			`NOOOOOOOOO!!!`,
			`Nubile slave boys.`,
			`on her left breast, a mole`,
			`One thousand Slim Jims.`,
			`Oversharing on social media`,
			`Panty raids.`,
			`Pistol-whipping a hostage.`,
			`Quiche.`,
			`Quivering jowls.`,
			`Revenge fucking.`,
			`Ripping into a man's chest and pulling out his still-beating heart.`,
			`Ryanair.`,
			`Salvia.`,
			`Sanding off a man's nose.`,
			`Santa cumming down your chimney.`,
			`Savagely beating a mascot.`,
			`Scrubbing under the folds.`,
			`sexual inadequacy`,
			`Sexy Siamese twins.`,
			`Shaft.`,
			`Shitting perfectly into a hot dog bun.`,
			`Slow motion.`,
			`Space muffins.`,
			`Statistically validated stereotypes.`,
			`Stockings filled with VaselineÂ®.`,
			`Suddenly feeling really sad for 40 years.`,
			`Suicide Awareness Training.`,
			`Syphilitic insanity.`,
			`The boogeyman.`,
			`The EDL.`,
			`The FantaÂ® girls.`,
			`The four arms of Vishnu.`,
			`The gun lobby`,
			`The harsh light of day.`,
			`The hidden dick in your favorite Disney movie.`,
			`The ooze.`,
			`The shambling corpse of Larry King.`,
			`The worst pain imaginable. Times two!`,
			`This guy!`,
			`Tripping elderly roller skaters.`,
			`Walking in on your mom dominating your dad.`,
			`Words, words, words.`,
			`Zeus's sexual appetites.`,
		},
	}
	AddPack(pack)
}

