package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Technology Pack",
		Description: "Technology and innovation themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The next big tech innovation will be %s.`},
			&PromptCard{Prompt: `Social media is ruined by %s.`},
			&PromptCard{Prompt: `Artificial intelligence will eventually %s.`},
			&PromptCard{Prompt: `If I could invent any technology, it would be %s.`},
			&PromptCard{Prompt: `The most annoying thing about modern technology is %s.`},
			&PromptCard{Prompt: `What tech advancement would change society forever?`},
		},
		Responses: []ResponseCard{
			`Virtual reality`,
			`Augmented reality`,
			`Artificial intelligence`,
			`Machine learning`,
			`Blockchain technology`,
			`Cryptocurrency`,
			`Quantum computing`,
			`Neural interfaces`,
			`Brain-computer interfaces`,
			`Teleportation`,
			`Time travel`,
			`Flying cars`,
			`Self-driving cars`,
			`Robots`,
			`Drones`,
			`3D printing`,
			`Nanotechnology`,
			`Gene editing`,
			`Genetic engineering`,
			`Cloning`,
			`Holographic displays`,
			`Gesture recognition`,
			`Voice recognition`,
			`Facial recognition`,
			`Biometric security`,
			`Internet of Things`,
			`5G networks`,
			`Quantum internet`,
			`Cybersecurity`,
			`Hacking`,
			`Data mining`,
			`Big data analytics`,
			`Cloud computing`,
			`Edge computing`,
			`Quantum encryption`,
			`Decentralized networks`,
			`Digital currency`,
			`Smart contracts`,
			`The metaverse`,
			`A technological singularity`,
		},
	}
	AddPack(pack)
}
