package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "PAX East 2013",
		Description: "PAX East 2013 promo cards for Cards Against Humanity",
		Prompts: []*PromptCard{
			{Prompt: "At PAX East, the attendees are going crazy over _.", NumPick: 1},
			{Prompt: "Every booth in the Expo Hall has a playable demo of _.", NumPick: 1},
			{Prompt: "Inside the sealed envelope is _.", NumPick: 1},
			{Prompt: "The new interactive fiction game features _.", NumPick: 1},
			{Prompt: "The official PAX East themed snack food is _.", NumPick: 1},
			{Prompt: "This year's cosplay sensation is someone dressed as _.", NumPick: 1},
		},
		Responses: []ResponseCard{
			"A Molly Guard.",
			"A sad boner.",
			"Aggressive cunnilingus.",
			"An uncontrollable ass and mouth that work in perfect synchronicity.",
			"Appropriate body types for video games.",
			"Binders full of women.",
			"Blowing the hell out of Dracula's asshole.",
			"Bubbles and SCIENCE!",
			"Cheap, plastic fantasy armor.",
			"Cock magic.",
			"Competitive hugging.",
			"Constructive criticism of the female form.",
			"Courtney Love's unspeakable crimes.",
			"Dead bodies in the cargo hold.",
			"Decapitation.",
			"Democratic socialism.",
			"Disembodied hair.",
			"Dressing for the job you want, not the job you have.",
			"Dry orgasms.",
			"Eating a hot dog backwards.",
			"Eight tons of uninsured motorists.",
			"Electromagnetic hypersensitivity.",
			"Etiquette.",
			"Everything.",
			"Exposing your genitalia to a minor.",
			"Feeling genuinely afraid for your life.",
			"Flip-flopping.",
			"Forty thousand screaming, dying horses.",
			"Frottage.",
			"Fungus.",
			"Genitalia.",
			"Getting caught in the in-between.",
			"Godwin's Law.",
			"Going back in time to stop World War II.",
			"Golden showers.",
			"Gonorrhea.",
			"Grand Theft Auto: Anabaptist.",
			"Grandiose delusions.",
			"Grindr.",
			"Grisly suicide.",
			"Growing a second skeleton.",
			"Growing a unibrow.",
			"Hallucinating being inside a girl.",
			"Ham fisting.",
			"Hanging with the Duchess of York.",
			"Happily married gay couples raising happy gay families.",
			"Hard dicks.",
			"Having your balls deflated.",
			"Hemmingway in Paris.",
			"Her scent was like a thousand waffle irons.",
			"Heretofore unknown semen receptacles.",
			"High-yield thermonuclear warfare.",
			"Hipsters.",
			"Hitler's lost testicle.",
			"Holding hands with someone you're not emotionally ready for.",
			"Homeopathy.",
			"Honey in the butthole.",
			"Hope.",
			"Howitzer.",
			"Human-ant hybrids.",
			"Hump-grinding your grandmother.",
			"Hyperbole and a Half.",
			"I dunno, man. This card is too abstract for me.",
			"I'm sorry, Dave. I'm afraid I can't do that.",
			"Immaculate conception.",
			"Impeachment.",
			"Impotence.",
			"In the butt.",
			"In vitro fertilization.",
			"Incest.",
			"Incredible things I did to her ass.",
			"Industrial-strength laxatives.",
			"Inevitable cultural hegemony of China.",
			"Ingratitude.",
			"Inheriting an Egyptian tomb.",
			"Injecting a serum that turns you into a waif.",
			"Injecting a serum that turns you into a werewolf.",
			"Injecting a serum that turns you into pure evil.",
			"Injecting fear in the hearts of men.",
			"Injecting LSD directly into the taint.",
			"Injecting spiders into your eyeballs.",
			"Inner beauty.",
			"Innocent laughter.",
			"Innocent tears.",
			"Innovation.",
			"Insanely relevant pop culture reference.",
			"Insanely relevant pop culture reference (X-Files version).",
			"Insane amounts of money.",
			"Insane amounts of money and senseless violence.",
			"Insect pheromones.",
			"Insecurity.",
			"Insensitive racism.",
			"Insincere concern.",
			"Inside every hardened criminal is a tiny dead child.",
			"Inside the mule is _.",
			"Insomnia.",
			"Insouciance.",
			"Inspiration.",
			"Inspired mediocrity.",
			"Install Windows!",
			"Installing the OS on a 386 machine.",
			"Installing Windows 98!",
			"Instinctively knowing what to do with a corpse.",
			"Institution.",
			"Instruction manual for a nuclear bomb.",
			"Insulting the President.",
			"Insult towards Jewish people in Yiddish.",
			"Insurance.",
			"Insurmountable wealth.",
			"Intact packages.",
			"Intangible goods.",
			"Intangible things.",
			"Integer overflow.",
			"Integral to the human condition.",
			"Integrated Systems Solutions Corporation.",
			"Integration with the Jetsons.",
			"Integument.",
			"Intellect.",
			"Intellectual honesty.",
			"Intellectual horsepower.",
			"Intellectual pretension.",
			"Intellectual property.",
			"Intellectually bankrupt.",
			"Intelligence.",
			"Intelligence agencies.",
			"Intelligentsia.",
			"Intelligible only to robots.",
			"Intense erotic friction.",
			"Intense negotiations between a tuna and sea biscuit.",
			"Intensity.",
			"Intentional abandonment.",
			"Intentional cruelty.",
			"Intentional double negatives.",
			"Intentional misuse of the prefix 'in-'.",
			"Intention tremor.",
			"Intentions of the founding fathers.",
			"Inter-species depravity.",
			"Interactive fiction.",
			"Interactive fiction that is entirely about dicks.",
			"Intercontinental ballistic missiles.",
			"Intercontinental marriage proposal.",
			"Intercourse with the unborn.",
			"Interdimensional portal filled with feces.",
			"Interdimensional rape.",
			"Interdimensional tentacle rape.",
			"Interesting.",
			"Interesting new ways to die.",
			"Interestingly-shaped objects.",
			"Interface between organic and inorganic matter.",
			"Interfaith dialogue.",
			"Interfaith donkey show.",
			"Interfaith relations.",
			"Interfaith relations in Jerusalem.",
			"Interfaith Slingblade role-play.",
			"Interfaith zombie soccer.",
			"Interfaith zombie soccer with rabid badgers.",
			"Interfaith zombie soccer with rabid badgers and explosives.",
			"Interfaith zombie soccer with rabid badgers, explosives, and tentacle rape.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, and an entirely new genre of music.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, and a mysterious, swashbuckling stranger.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, and a special appearance by Oprah.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, and seventeen alternate endings.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, seventeen alternate endings, and your mom.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, seventeen alternate endings, your mom, and a dragon.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, seventeen alternate endings, your mom, a dragon, and a new Infiniti QX56.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, seventeen alternate endings, your mom, a dragon, a new Infiniti QX56, and a mysterious card that makes the game never end.",
			"Interfaith zombie soccer with rabid badgers, explosives, tentacle rape, an entirely new genre of music, a mysterious, swashbuckling stranger, a special appearance by Oprah, seventeen alternate endings, your mom, a dragon, a new Infiniti QX56, a mysterious card that makes the game never end, and a feeling of cosmic existential dread.",
		},
	}
	AddPack(pack)
}
