package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "CAH: Green Box Expansion",
		Description: "CAH: Green Box Expansion pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `_ be all like _.`},
			&PromptCard{Prompt: `_: Brought to you by _.`},
			&PromptCard{Prompt: `Art isn't just a painting in a stuffy museum. Art is alive. Art is _.`},
			&PromptCard{Prompt: `As reparations for slavery, all African Americans will receive _.`},
			&PromptCard{Prompt: `As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and _.`},
			&PromptCard{Prompt: `Best you go back where you came from, now. We don't take too kindly to _ in these parts.`},
			&PromptCard{Prompt: `CNN breaking news! Scientists discover _.`},
			&PromptCard{Prompt: `Coming to Red Lobster® this month, _.`},
			&PromptCard{Prompt: `Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you _.`},
			&PromptCard{Prompt: `Dance like there's nobody watching, love like you'll never be hurt, and live like you're _.`},
			&PromptCard{Prompt: `Errbody in the club _.`},
			&PromptCard{Prompt: `Feeling so grateful! #amazing #mylife #_.`},
			&PromptCard{Prompt: `Girls just wanna have _.`},
			&PromptCard{Prompt: `Google Calendar alert: _ in 10 minutes.`},
			&PromptCard{Prompt: `I don't believe in God. I believe in _.`},
			&PromptCard{Prompt: `I got rhythm, I've got music, I've got _. Who could ask for anything more?`},
			&PromptCard{Prompt: `I may not be much to look at, but I fuck like _.`},
			&PromptCard{Prompt: `I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like _.`},
			&PromptCard{Prompt: `I'll take the BBQ bacon burger with friend egg and fuck it how about _.`},
			&PromptCard{Prompt: `I'm sorry, sir, but your insurance plan doesn't cover injuries caused by _.`},
			&PromptCard{Prompt: `I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw _.`},
			&PromptCard{Prompt: `If at first you don't succeed, try _.`},
			&PromptCard{Prompt: `In the 1950s, psychologists prescribed _ as a cure for homosexually.`},
			&PromptCard{Prompt: `LSD + _ = really bad time.`},
			&PromptCard{Prompt: `Mom's to-do list:
 * Buy Groceries
 * Clean up _.
 * Soccer Practice.`},
			&PromptCard{Prompt: `Most Americans would not vote for a candidate who is openly _.`},
			&PromptCard{Prompt: `No, no, no, no, no, no, NO! I will NOT let _ ruin this wedding.`},
			&PromptCard{Prompt: `Oh no! Siri, how do I fix _?`},
			&PromptCard{Prompt: `One more thing. Watch out for Big Mike. They say he killed a man with _.`},
			&PromptCard{Prompt: `Ooo, daddy like _.`},
			&PromptCard{Prompt: `Poor Brandon, still living in his parent's basement. I heard he never got over _.`},
			&PromptCard{Prompt: `Run, run, as fast as you can! You can't catch me, I'm _!`},
			&PromptCard{Prompt: `She's a lady in the streets, _ in the sheets.`},
			&PromptCard{Prompt: `She's just one of the guys, you know? She likes beer, and football, and _.`},
			&PromptCard{Prompt: `Son, take it from someone who's been around the block a few times. Nothin' puts her in the mood like _.`},
			&PromptCard{Prompt: `Summer lovin', had me a blast. _, happened so fast.`},
			&PromptCard{Prompt: `The top Google auto-complete results for "Barack Obama":
Barack Obama Height.
Barack Obama net worth.
Barack Obama _.`},
			&PromptCard{Prompt: `Then the princess kissed the frog, and all of a sudden the frog was _!`},
			&PromptCard{Prompt: `There is no God. It's just _ and then you die.`},
			&PromptCard{Prompt: `This Friday at the Liquid Lunge, it's _ Night! Ladies drink free.`},
			&PromptCard{Prompt: `We do not shake with our left hands in this country. That is the hand we use for _.`},
			&PromptCard{Prompt: `Well if _ is a crime, then lock me up!`},
			&PromptCard{Prompt: `Well, shit. My eyes ain't so good, but I'll eat my own boot if that ain't _!`},
			&PromptCard{Prompt: `What are all those whales singing about?`},
			&PromptCard{Prompt: `What sucks balls?`},
			&PromptCard{Prompt: `What totally destroyed my asshole?`},
			&PromptCard{Prompt: `What turned me into a Republican?`},
			&PromptCard{Prompt: `What will end racism once and for all?`},
			&PromptCard{Prompt: `What's a total waste of Hillary Clinton's time?`},
			&PromptCard{Prompt: `What's about to take dance floor to the next level?`},
			&PromptCard{Prompt: `What's the gayest?`},
			&PromptCard{Prompt: `What's the most problematic?`},
			&PromptCard{Prompt: `Why am I laughing and crying and taking off my clothes?`},
			&PromptCard{Prompt: `With a one-time gift of just $10, you can save this child from _.`},
			&PromptCard{Prompt: `You know who else liked _? Hitler.`},
			&PromptCard{Prompt: `You won't believe what's in my pussy. It's _.`},
		},

		Responses: []ResponseCard{
			`10 football players with erections barrelling towards you at full speed.`,
			`10,000 shrieking teenage girls.`,
			`A big ol' plate of fettuccini alfredo.`,
			`A big, beautiful mouth packed to the brim with sparkling white teeth.`,
			`A black friend.`,
			`A burrito that's just sour cream.`,
			`A cheerfulness that belies a deep-seated self-loathing.`,
			`A cold and indifferent universe.`,
			`A creature made of penises that must constantly arouse itself to survive.`,
			`A creepy child singing a nursery rhyme.`,
			`A dolphin that learns to talk and becomes the Dean of Harvard Law School.`,
			`A duffel bag full of lizards.`,
			`A finger up the butt.`,
			`A genetic predisposition for alcoholism.`,
			`A gun that shoots cobras.`,
			`A hug.`,
			`A long business meeting with no obvious purpose.`,
			`A man in a suit with perfect hair who tells you beautiful lies.`,
			`A man with the head of a goat and the body of a goat.`,
			`A massive collection of child pornography.`,
			`A medium horchata.`,
			`A negative body image that is totally justified.`,
			`A slowly encroaching circle of wolves.`,
			`A strong horse and enough rations for thirty days.`,
			`A terrified fat child who won't come out of the bushes.`,
			`A tiny fireman who puts out tiny fires.`,
			`A weird guy who says weird stuff and weirds me out.`,
			`A woman's perspective.`,
			`A woman's right to choose.`,
			`Aborting the shit out of a fetus.`,
			`Albert Einstein but if he had huge muscles and a rhinoceros cock.`,
			`All the people I've killed.`,
			`An arrangement wherein I give a person money and they have sex with me.`,
			`An empowered woman.`,
			`An incurable homosexual.`,
			`An old dog dragging its anus across the floor.`,
			`An old dog full of tumors.`,
			`An older man.`,
			`An X-Man whose power is that he has sex with dogs and children.`,
			`Anal.`,
			`Antidepressants.`,
			`Art.`,
			`Assassinating the president.`,
			`Awesome pictures of planets and stuff.`,
			`Bad emotions I don't want.`,
			`Becoming the President of the United States.`,
			`Being sexually attracted to children.`,
			`Being turned into sausages.`,
			`Beyonce.`,
			`Big, smart money boys tap-tapping on their keyboards.`,
			`Blossoming into a beautiful young woman.`,
			`Breastfeeding in public like a radiant earth goddess.`,
			`Brunch.`,
			`Catching a live salmon in your mouth.`,
			`Child labor.`,
			`Chinese campaign clothing.`,
			`Chipotle.`,
			`Chris Hemsworth.`,
			`Comprehensive immigration reform.`,
			`Condoleezza Rice.`,
			`Consensual, nonreproductive incest.`,
			`Content.`,
			`Crazy anal orgasms.`,
			`Creamy slices of real, California avocado.`,
			`Critical thinking.`,
			`Crushing the patriarchy.`,
			`Daddy going away forever.`,
			`Defeating a gorilla in single combat.`,
			`Denying the Holocaust.`,
			`Dis bitch.`,
			`Discovering that what I really want in life is to kill people and have sex with their corpses.`,
			`Doing a somersault and barfing.`,
			`Dominating a man by peeing on his eldest son.`,
			`Doritos and a Fruit Roll-Up.`,
			`Dropping dead in a Sbarro's bathroom and not being found for 72 hours.`,
			`Dumpster juice.`,
			`Eating ass.`,
			`Eating pebbles, shitting the pebbles, the eating the shit-pebbles, and then shitting those pebbles again.`,
			`Eating people.`,
			`Eating too many Cinnabons and then vomiting and then eating the vomit.`,
			`Ejaculating at the apex of a cartwheel.`,
			`Esmeralda, my most beautiful daughter.`,
			`Eternal screaming madness.`,
			`Every man's ultimate fantasy: a perfectly cylindrical vagina.`,
			`everything's for sale`,
			`Exploring each other's buttholes.`,
			`Facilitating dialogue and deconstructing binaries.`,
			`Falling into a pit of waffles.`,
			`Farting a huge shit out of my pussy.`,
			`Farting all over my face with your tight little asshole.`,
			`Feeling the emotion of anger.`,
			`Feminist men.`,
			`Film roles for actresses over 40.`,
			`Finding a nice elevator to poop in.`,
			`Forty-five minutes of finger blasting.`,
			`Founding a major world religion.`,
			`Fucking me good and taking me to Red Lobster.®`,
			`Fucking my therapist.`,
			`Gary.`,
			`Gay thoughts.`,
			`Gayle from HR.`,
			`Gazpacho.`,
			`Getting aborted.`,
			`Getting blasted in the face by a t-shirt cannon.`,
			`Getting eaten out by a dog.`,
			`Getting high with mom.`,
			`Getting killed and dragged up a tree by a leopard.`,
			`Getting laid like all the time.`,
			`Getting naked too soon.`,
			`Getting pegged.`,
			`Getting the Dorito crumbs out of my pubes.`,
			`Getting this party started!`,
			`Getting trapped in a conversation about Ayn Rand.`,
			`Going around pulling people's tampons out.`,
			`Going to bed at a reasonable hour.`,
			`Gregor, my largest son.`,
			`Grunting for ten minutes and then peeing sand.`,
			`Gus: the Palsy Cat.`,
			`Happy daddies with happy sandals.`,
			`Hating Jews.`,
			`Having a vagina.`,
			`Having an awesome time drinking and driving.`,
			`Having sex with a beautiful person.`,
			`Having sex with a man and then eating his head.`,
			`Having sex with your mom.`,
			`Holding the proper political beliefs of my time to attract a mate.`,
			`Homework.`,
			`Hot lettuce.`,
			`How good lead paint taste.`,
			`How great my ass looks in these jeans.`,
			`How sad it will be when Morgan Freeman dies.`,
			`How strange it is to be anything at all.`,
			`Huge big balls full of jizz.`,
			`Informing you that I am a registered sex offender.`,
			`ISIS.`,
			`It being too late to stop having sex with a horse.`,
			`Jason, the teen mayor.`,
			`Jazz.`,
			`Jeff Bezos.`,
			`Just now finding out about the Armenian Genocide.`,
			`Late-stage dementia.`,
			`Libertarians.`,
			`Loud, scary thunder.`,
			`Making out and stuff.`,
			`Math.`,
			`Meatloaf, the food.`,
			`Meatloaf, the man.`,
			`Melissa McCarthyism.`,
			`Menopause.`,
			`Mental illness.`,
			`Microaggressions.`,
			`Misogyny.`,
			`Mixing M&Ms and Skittles like some kind of psychopath.`,
			`Mommy and daddy fighting all the time.`,
			`Moon people.`,
			`Munchin' puss.`,
			`My brother's hot friends.`,
			`My dog dying.`,
			`My huge penis and substantial fortune.`,
			`Objectifying women.`,
			`One of them big-city Jew lawyers.`,
			`One of those "blow jobs" I've been hearing so much about.`,
			`Onions.`,
			`Opening your mouth to talk and a big penis flops out.`,
			`Our baby.`,
			`Out-of-control teenage blowjob parties.`,
			`Overthrowing the democratically-elected government of Chile.`,
			`Participating.`,
			`Period poops.`,
			`Picking up a glass of water and taking a sip and being the president.`,
			`Playing my asshole like a trumpet.`,
			`Plowing that ass like a New England corn farmer.`,
			`Political correctness.`,
			`Pooping in a leotard and hoping no one notices.`,
			`Pooping in the potty.`,
			`Prematurely ejaculating like a total loser.`,
			`Pretending to be one of the guys but actually being the spider god.`,
			`Putting more black people in jail.`,
			`Quacking like a duck in lieu of a cogent argument.`,
			`Quinoa.`,
			`Raising three kids on minimum wage.`,
			`Reaching an age where barbecue chips are better than sex.`,
			`Regurgitating a half-digested sparrow.`,
			`Restoring Germany to its former glory.`,
			`Rock-hard tits and a huge vagina.`,
			`Rolling so hard.`,
			`Rubbing my bush all over your bald head.`,
			`Salsa Night at Dave's Cantina.`,
			`Scissoring, if that's a thing.`,
			`Seizing control of the means of production.`,
			`Self-identifying as a DJ.`,
			`Showering praise upon the Sultan's hideous daughters.`,
			`Showing all the boys my pussy.`,
			`Slamming a dunk.`,
			`Smashing my balls at the moment of climax.`,
			`Some of that good dick.`,
			`Some real spicy shrimps.`,
			`Starting a shitty podcast.`,
			`Straight blazin' 24/7.`,
			`Sucking each other's penises for hours on end.`,
			`Sudden and unwanted slam poetry.`,
			`Systems and policies designed to preserve centuries-old power structures.`,
			`Tables.`,
			`Taking the form of a falcon.`,
			`Tender chunks of all-white-meat chicken.`,
			`That bitch, Stacy.`,
			`That chicken from Popeyes. ®`,
			`The amount of baby carrots I can fit up my ass.`,
			`The best, deepest quotes from The Dark Knight.`,
			`The body of a 46-year-old man.`,
			`The bond between a woman and her horse.`,
			`The clown that followed me home from the grocery store.`,
			`The fear and hatred in men's hearts.`,
			`The feeling of going to McDonald's as a 6-year-old.`,
			`The flaming wreckage of the International Space Station.`,
			`The full force of the American military.`,
			`The full-blown marginalization of ugly people.`,
			`The government.`,
			`The graceful path of an autumn leaf as it falls to its earthen cradle.`,
			`The hottest MILF in Dallas.`,
			`The LGBT community.`,
			`The lived experience of African Americans.`,
			`The mysterious fog rolling into town.`,
			`The ol' penis-in-the-popcorn surprise.`,
			`The Rwandan Genocide.`,
			`The secret to truly resilient hair.`,
			`The sweet, forbidden meat of the monkey.`,
			`The wind.`,
			`Thinking about what eating even is.`,
			`Three hours of nonstop penetration.`,
			`Tiny, rancid girl farts.`,
			`Trees.`,
			`Trevor, the world's greatest boyfriend.`,
			`Turning 32.`,
			`Twenty bucks.`,
			`Twenty cheerleaders laughing at your tiny penis.`,
			`Twisting my cock and balls into a balloon poodle.`,
			`Two beautiful pig sisters.`,
			`Two shitty kids and a garbage husband.`,
			`Waking up inside of a tornado.`,
			`Watching a hot person eat.`,
			`Watching you die.`,
			`Water.`,
			`When the big truck goes "Toot! Toot!"`,
			`Who really did 9/11.`,
			`Whomsoever let the dogs out.`,
			`Whooping your ass at Mario Kart.`,
			`Working so hard to have muscles and then having them.`,
			`You.`,
		},
	}

	AddPack(pack)
}
