package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "music-pack",
		Description: "Music and musicians themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The best song ever written was about %s.`},
			&PromptCard{Prompt: `Great musicians have a gift for %s.`},
			&PromptCard{Prompt: `No concert is complete without %s.`},
			&PromptCard{Prompt: `The most controversial music genre is %s.`},
			&PromptCard{Prompt: `I always cry when I listen to %s.`},
			&PromptCard{Prompt: `What's the best type of music to make love to?`},
		},
		Responses: []ResponseCard{
			`The power of love`,
			`Heartbreak`,
			`Lost love`,
			`Forbidden love`,
			`Unrequited love`,
			`A broken heart`,
			`Dancing`,
			`Partying`,
			`Getting drunk`,
			`Rebellion`,
			`Freedom`,
			`Social justice`,
			`Civil rights`,
			`Revolution`,
			`Peace`,
			`Hope and inspiration`,
			`Despair and pain`,
			`Rage and anger`,
			`Sex and seduction`,
			`Passion and desire`,
			`Money and fame`,
			`Cars and girls`,
			`Drugs and excess`,
			`Violence and crime`,
			`Fast guitars`,
			`Heavy bass`,
			`Sick beats`,
			`Smooth vocals`,
			`Powerful instrumentation`,
			`Intense emotion`,
			`Catchy melody`,
			`Unforgettable chorus`,
			`Mind-blowing lyrics`,
			`Perfect harmony`,
			`Epic arrangements`,
			`Studio wizardry`,
			`Live performance energy`,
			`The magic of music`,
			`The power of sound`,
			`A beautiful noise`,
		},
	}
	AddPack(pack)
}
