package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "Travel Pack",
		Description: "Travel and exploration themed card pack",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `The best vacation includes %s.`},
			&PromptCard{Prompt: `I would never travel anywhere with %s.`},
			&PromptCard{Prompt: `The most amazing travel experience is %s.`},
			&PromptCard{Prompt: `When traveling, always remember to bring %s.`},
			&PromptCard{Prompt: `The worst travel companion is someone who %s.`},
			&PromptCard{Prompt: `What's the most important thing for a perfect vacation?`},
		},
		Responses: []ResponseCard{
			`A beach resort`,
			`Mountain scenery`,
			`A jungle adventure`,
			`Desert exploration`,
			`Polar expeditions`,
			`Exotic locales`,
			`Historical sites`,
			`Cultural immersion`,
			`Local cuisine`,
			`Street food`,
			`Fine dining`,
			`A five-star hotel`,
			`A luxury cruise`,
			`A private jet`,
			`A safari`,
			`Snorkeling or scuba diving`,
			`Zip-lining through rainforests`,
			`Rock climbing`,
			`Bungee jumping`,
			`Skydiving`,
			`Adventure sports`,
			`Wildlife encounters`,
			`Exotic animals`,
			`Pristine beaches`,
			`Crystal clear waters`,
			`Stunning sunsets`,
			`Northern lights`,
			`A guided tour`,
			`Traveling solo`,
			`Traveling with friends`,
			`A romantic getaway`,
			`A family vacation`,
			`Spring break`,
			`Summer vacation`,
			`Gap year travel`,
			`Backpacking`,
			`A road trip`,
			`A train journey`,
			`A cruise`,
			`A pilgrimage`,
		},
	}
	AddPack(pack)
}
